export const FIGHTER_ARCHETYPES = Object.freeze({
  falcon: Object.freeze({
    id: 'falcon',
    displayName: 'Captain Falcon',
    width: 42,
    height: 82,
    ecb: Object.freeze({ width: 30, height: 82 }),
    hurtbubbles: Object.freeze([
      Object.freeze({ id: 'head', offsetX: 0, offsetY: -68, radius: 13, rx: 13, ry: 13 }),
      Object.freeze({ id: 'chest', offsetX: 0, offsetY: -48, radius: 16, rx: 16, ry: 16 }),
      Object.freeze({ id: 'hips', offsetX: 0, offsetY: -28, radius: 18, rx: 17, ry: 18 }),
      Object.freeze({ id: 'front-arm', offsetX: 16, offsetY: -46, radius: 12, rx: 8, ry: 12 }),
      Object.freeze({ id: 'back-arm', offsetX: -16, offsetY: -46, radius: 12, rx: 8, ry: 12 }),
      Object.freeze({ id: 'front-thigh', offsetX: 13, offsetY: -15, radius: 15, rx: 9, ry: 15 }),
      Object.freeze({ id: 'back-thigh', offsetX: -13, offsetY: -15, radius: 15, rx: 9, ry: 15 }),
      Object.freeze({ id: 'front-foot', offsetX: 12, offsetY: 3, radius: 9, rx: 9, ry: 8 }),
      Object.freeze({ id: 'back-foot', offsetX: -12, offsetY: 3, radius: 9, rx: 9, ry: 8 }),
    ]),
    stickDeadzone: 0.16,
    walkThreshold: 0.62,
    runThreshold: 0.62,
    dashThreshold: 0.72,
    dashTapThreshold: 0.72,
    dashTapFrames: 9,
    dashInitialSpeed: 2.45,
    initialDashFrames: 9,
    dashFrames: 9,
    dashDanceWindowFrames: 9,
    dashTurnSpeed: 2.15,
    walkAcceleration: 0.20,
    runAcceleration: 0.27,
    turnaroundAcceleration: 0.43,
    airAcceleration: 0.17,
    airTurnAcceleration: 0.23,
    maxWalkSpeed: 2.25,
    walkSpeed: 2.25,
    maxGroundSpeed: 5.05,
    maxRunSpeed: 5.05,
    runSpeed: 5.05,
    dashAcceleration: 0.054,
    dashSpeed: 5.05,
    maxAirSpeed: 5.35,
    airFriction: 0.997,
    traction: 0.68,
    brakeTraction: 0.58,
    skidTraction: 0.62,
    gravity: 0.58,
    weight: 1.0,
    fastFallGravity: 0.58,
    maxFallSpeed: 10.4,
    fastFallSpeed: 15.5,
    jumpSquatFrames: 4,
    jumpVelocity: -14.1,
    fullHopVelocity: -14.1,
    shortHopVelocity: -9.3,
    doubleJumpVelocity: -12.2,
    maxJumps: 2,
    landingLagFrames: 4,
    hardLandingLagFrames: 7,
    crouchThreshold: 0.34,
    platformDropThreshold: 0.86,
    platformDropFrames: 14,
    fastFallTapFrames: 22,
    ledgeSnapX: 58,
    ledgeSnapTop: 42,
    ledgeSnapBottom: 96,
    ledgeHangYOffset: 62,
    ledgeJumpVelocity: -12.8,
    ledgeJumpInwardSpeed: 3.25,
    ledgeGetupFrames: 18,
    ledgeReleaseLockoutFrames: 18,
    damage: 0,
    attacks: Object.freeze({
      neutral: Object.freeze({
        id: 'gentleman-jab',
        startup: 3,
        active: 3,
        recovery: 10,
        totalFrames: 16,
        hitbubbles: Object.freeze([
          Object.freeze({
            id: 'jab-1',
            offsetX: 35,
            offsetY: -39,
            radius: 12,
            damage: 4,
            angle: -35,
            baseKnockback: 3.4,
            knockbackGrowth: 0.06,
            hitstun: 12,
          }),
          Object.freeze({
            id: 'jab-1-shoulder',
            offsetX: 24,
            offsetY: -42,
            radius: 9,
            damage: 4,
            angle: -35,
            baseKnockback: 3.4,
            knockbackGrowth: 0.06,
            hitstun: 12,
          }),
        ]),
      }),
      forward: Object.freeze({
        id: 'raptor-lunge',
        startup: 8,
        active: 5,
        recovery: 18,
        totalFrames: 31,
        hitbubbles: Object.freeze([
          Object.freeze({
            id: 'lunge-knee',
            offsetX: 50,
            offsetY: -37,
            radius: 16,
            damage: 11,
            angle: -26,
            baseKnockback: 6.8,
            knockbackGrowth: 0.11,
            hitstun: 22,
          }),
        ]),
      }),
    }),
  }),
  vanguard: Object.freeze({
    id: 'vanguard',
    displayName: 'Vanguard',
    width: 18,
    height: 42,
    hurtbubbles: Object.freeze([
      Object.freeze({ id: 'head', offsetX: 0, offsetY: -36, radius: 7 }),
      Object.freeze({ id: 'chest', offsetX: 0, offsetY: -25, radius: 9 }),
      Object.freeze({ id: 'hips', offsetX: 0, offsetY: -14, radius: 8 }),
    ]),
    walkAcceleration: 0.8,
    walkSpeed: 1.8,
    runAcceleration: 0.9,
    dashAcceleration: 1.1,
    airAcceleration: 0.35,
    maxGroundSpeed: 5.2,
    runSpeed: 5.8,
    dashSpeed: 6.3,
    walkThreshold: 0.18,
    runThreshold: 0.62,
    dashThreshold: 0.78,
    dashFrames: 10,
    maxAirSpeed: 4.4,
    traction: 0.52,
    gravity: 0.42,
    fastFallGravity: 0.72,
    maxFallSpeed: 8.5,
    jumpSquatFrames: 3,
    jumpVelocity: -8.2,
    fullHopVelocity: -8.2,
    shortHopVelocity: -5,
    doubleJumpVelocity: -7.2,
    maxJumps: 2,
    landingLagFrames: 4,
    damage: 0,
    attacks: Object.freeze({
      neutral: Object.freeze({
        id: 'straight-punch',
        startup: 4,
        active: 3,
        recovery: 12,
        totalFrames: 19,
        hitbubbles: Object.freeze([
          Object.freeze({
            id: 'punch',
            offsetX: 23,
            offsetY: -24,
            radius: 10,
            damage: 5,
            angle: -30,
            baseKnockback: 4,
            knockbackGrowth: 0.08,
            hitstun: 14,
          }),
        ]),
      }),
    }),
  }),
  comet: Object.freeze({
    id: 'comet',
    displayName: 'Comet',
    width: 16,
    height: 36,
    hurtbubbles: Object.freeze([
      Object.freeze({ id: 'head', offsetX: 0, offsetY: -31, radius: 6 }),
      Object.freeze({ id: 'chest', offsetX: 0, offsetY: -21, radius: 8 }),
      Object.freeze({ id: 'hips', offsetX: 0, offsetY: -11, radius: 7 }),
    ]),
    walkAcceleration: 0.95,
    walkSpeed: 2.1,
    runAcceleration: 1,
    dashAcceleration: 1.25,
    airAcceleration: 0.44,
    maxGroundSpeed: 6.4,
    runSpeed: 6.8,
    dashSpeed: 7.4,
    walkThreshold: 0.18,
    runThreshold: 0.62,
    dashThreshold: 0.78,
    dashFrames: 9,
    maxAirSpeed: 5.1,
    traction: 0.42,
    gravity: 0.36,
    fastFallGravity: 0.62,
    maxFallSpeed: 7.8,
    jumpSquatFrames: 2,
    jumpVelocity: -7.8,
    fullHopVelocity: -7.8,
    shortHopVelocity: -4.8,
    doubleJumpVelocity: -7.1,
    maxJumps: 2,
    landingLagFrames: 3,
    damage: 0,
    attacks: Object.freeze({
      neutral: Object.freeze({
        id: 'quick-palm',
        startup: 3,
        active: 2,
        recovery: 9,
        totalFrames: 14,
        hitbubbles: Object.freeze([
          Object.freeze({
            id: 'palm',
            offsetX: 19,
            offsetY: -20,
            radius: 9,
            damage: 3,
            angle: -32,
            baseKnockback: 3.2,
            knockbackGrowth: 0.07,
            hitstun: 10,
          }),
        ]),
      }),
    }),
  }),
});
