export const CONFIG = Object.freeze({
  tickRate: 60,
  canvas: { width: 1280, height: 720 },
  arena: { left: 70, right: 1210, ceiling: 55, floor: 620 },
  round: { countdownTicks: 180, roundOverTicks: 60, winsNeeded: 3 },
  player: {
    standingWidth: 44,
    standingHeight: 118,
    crouchingWidth: 48,
    crouchingHeight: 64,
    groundAccel: 1.5,
    groundReverseAccel: 2.2,
    maxRunSpeed: 8.8,
    groundFriction: 0.74,
    crouchFriction: 0.48,
    airAccel: 0.52,
    maxAirSpeed: 6.8,
    airDrag: 0.988,
    gravity: 0.74,
    maxFallSpeed: 18.5,
    fastFallSpeed: 16.5,
    jumpSquatFrames: 3,
    fullHopVelocity: -17,
    shortHopVelocity: -12.5,
    dashFrames: 7,
    spotDodge: { startup: 3, active: 7, total: 22 },
    airDodge: { startup: 2, active: 6, total: 20, speed: 9.5 },
    groundAttack: { startup: 10, active: 3, total: 29 },
    airAttack: { startup: 7, active: 3, total: 23, forwardBoost: 1.1 },
  },
  ball: {
    radius: 12,
    baseSpeed: 6.25,
    wallSpeedMultiplier: 1.0045,
    returnSpeedMultiplier: 1.115,
    maxCollisionIterations: 256,
    launchAngleMin: 18,
    launchAngleMax: 52,
  },
  render: { spriteScale: 0.31 },
});
