// Class routes, skills, and passives data. All Strength route tiers are defined here.
// Other routes are added here as they are scoped in CLASS_SKILLS_AND_PASSIVES_CANON.md.
// Nothing executes in this file — pure data only.

// ── Skill definitions ─────────────────────────────────────────────────────────

const CLASS_SKILLS = [
  // ── Strength Tier 1 — Apprentice ─────────────────────────────────────────
  {
    id: 'cleave',
    name: 'Cleave',
    family: 'cleave',
    rank: 1,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'percentMP',
    costAmount: 0.05,
    targeting: 'single',
    description: 'Deals physical damage ignoring the target\'s Defense.',
    tiered: true,
  },
  {
    id: 'temper',
    name: 'Temper',
    family: 'temper',
    rank: 1,
    classRoute: 'strength',
    category: 'setup',
    costType: 'flatMP',
    costAmount: 10,
    targeting: 'self',
    description: 'Raises the user\'s Strength for 2 turns.',
    tiered: true,
  },
  {
    id: 'reckless_strike',
    name: 'Reckless Strike',
    family: 'reckless_strike',
    rank: 1,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'Deals heavy physical damage; user takes a fixed amount of recoil damage.',
    tiered: true,
  },
  {
    id: 'final_strike',
    name: 'Final Strike',
    family: 'final_strike',
    rank: 1,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'single',
    description: 'Deals physical damage that increases as the user\'s HP decreases; modest scaling at this tier.',
    tiered: true,
  },
  {
    id: 'finishing_blow',
    name: 'Finishing Blow',
    family: 'finishing_blow',
    rank: 1,
    classRoute: 'strength',
    category: 'finisher',
    costType: 'flatMP',
    costAmount: 14,
    targeting: 'single',
    description: 'Deals physical damage with a significant bonus when the target is below 30% HP.',
    tiered: false,
  },

  // ── Strength Tier 2 — Squire ──────────────────────────────────────────────
  {
    id: 'cleave_2',
    name: 'Cleave II',
    family: 'cleave',
    rank: 2,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'percentMP',
    costAmount: 0.05,
    targeting: 'single',
    description: 'Upgraded Cleave. Deals physical damage ignoring the target\'s Defense, with increased power over Cleave.',
    tiered: true,
  },
  {
    id: 'reckless_strike_2',
    name: 'Reckless Strike II',
    family: 'reckless_strike',
    rank: 2,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'Upgraded Reckless Strike. Deals heavier physical damage; user takes increased recoil damage.',
    tiered: true,
  },
  {
    id: 'challenge',
    name: 'Challenge',
    family: 'challenge',
    rank: 1,
    classRoute: 'strength',
    category: 'utility',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'Forces the target to direct their next action at the user. No damage.',
    tiered: false,
  },
  {
    id: 'power_through',
    name: 'Power Through',
    family: 'power_through',
    rank: 1,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'single',
    description: 'Deals physical damage and restores a small amount of the user\'s HP based on damage dealt.',
    tiered: false,
  },
  {
    id: 'brace',
    name: 'Brace',
    family: 'brace',
    rank: 1,
    classRoute: 'strength',
    category: 'defensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'User braces for impact this turn, reducing incoming physical damage. If the user takes damage while Braced, they are locked into executing Counter Strike on their next turn regardless of input.',
    tiered: false,
  },

  // ── Strength Tier 3 — Knight ──────────────────────────────────────────────
  {
    id: 'temper_2',
    name: 'Temper II',
    family: 'temper',
    rank: 2,
    classRoute: 'strength',
    category: 'setup',
    costType: 'flatMP',
    costAmount: 10,
    targeting: 'self',
    description: 'Upgraded Temper. Raises the user\'s Strength for a greater amount or longer duration.',
    tiered: true,
  },
  {
    id: 'final_strike_2',
    name: 'Final Strike II',
    family: 'final_strike',
    rank: 2,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'single',
    description: 'Upgraded Final Strike. Deals physical damage that increases as the user\'s HP decreases; stronger scaling than Final Strike.',
    tiered: true,
  },
  {
    id: 'war_stance',
    name: 'War Stance',
    family: 'war_stance',
    rank: 1,
    classRoute: 'strength',
    category: 'setup',
    costType: 'selfDebuff',
    costAmount: 0,
    targeting: 'self',
    description: 'Raises the user\'s physical damage output but lowers Speed for 2 turns.',
    tiered: false,
  },
  {
    id: 'sweep',
    name: 'Sweep',
    family: 'sweep',
    rank: 1,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 16,
    targeting: 'all_enemies',
    description: 'Deals physical damage to all enemies. Damage is reduced per target following standard multi-target scaling.',
    tiered: true,
  },
  {
    id: 'courage_strike',
    name: 'Courage Strike',
    family: 'courage_strike',
    rank: 1,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'percentHP',
    costAmount: 0.5,
    targeting: 'single',
    description: 'The user sacrifices half their current HP. They are locked out of action selection for the wind-up turn. On the following turn they automatically execute a massive physical strike.',
    tiered: false,
  },

  // ── Strength Tier 4 — Hero ────────────────────────────────────────────────
  {
    id: 'cleave_3',
    name: 'Cleave III',
    family: 'cleave',
    rank: 3,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'percentMP',
    costAmount: 0.05,
    targeting: 'single',
    description: 'Upgraded Cleave. Deals physical damage ignoring the target\'s Defense at maximum power.',
    tiered: true,
  },
  {
    id: 'reckless_strike_3',
    name: 'Reckless Strike III',
    family: 'reckless_strike',
    rank: 3,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'Upgraded Reckless Strike. Deals the heaviest physical damage of any Reckless Strike rank; recoil damage is at its highest.',
    tiered: true,
  },
  {
    id: 'sweep_2',
    name: 'Sweep II',
    family: 'sweep',
    rank: 2,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 16,
    targeting: 'all_enemies',
    description: 'Upgraded Sweep. Deals stronger AoE physical damage to all enemies.',
    tiered: true,
  },
  {
    id: 'rally_cry',
    name: 'Rally Cry',
    family: 'rally_cry',
    rank: 1,
    classRoute: 'strength',
    category: 'setup',
    costType: 'none',
    costAmount: 0,
    targeting: 'all_allies',
    description: 'Raises physical damage output for all active allies for 1 turn. No damage.',
    tiered: false,
  },
  {
    id: 'heroic_surge',
    name: 'Heroic Surge',
    family: 'heroic_surge',
    rank: 1,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'mixed',
    costAmount: 0,
    targeting: 'single',
    description: 'Only usable when the user is the last creature standing on their team. Deals significant single-target physical damage.',
    tiered: false,
  },

  // ── Strength Tier 5 — Kingslayer ──────────────────────────────────────────
  {
    id: 'temper_3',
    name: 'Temper III',
    family: 'temper',
    rank: 3,
    classRoute: 'strength',
    category: 'setup',
    costType: 'flatMP',
    costAmount: 10,
    targeting: 'self',
    description: 'Upgraded Temper. Raises the user\'s Strength at maximum potency for the longest duration.',
    tiered: true,
  },
  {
    id: 'final_strike_3',
    name: 'Final Strike III',
    family: 'final_strike',
    rank: 3,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'single',
    description: 'Upgraded Final Strike. Deals physical damage that scales maximally with the user\'s missing HP.',
    tiered: true,
  },
  {
    id: 'sweep_3',
    name: 'Sweep III',
    family: 'sweep',
    rank: 3,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 16,
    targeting: 'all_enemies',
    description: 'Upgraded Sweep. Deals the strongest AoE physical damage to all enemies.',
    tiered: true,
  },
  {
    id: 'defiant',
    name: 'Defiant',
    family: 'defiant',
    rank: 1,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'If the user was hit by a super effective move last turn, this turn they execute a Strength-boosted physical attack. Only activates under that condition.',
    tiered: false,
  },
  {
    id: 'castlebreaker',
    name: 'Castlebreaker',
    family: 'castlebreaker',
    rank: 1,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 18,
    targeting: 'single',
    description: 'Deals physical damage that scales upward with the target\'s Defense — the higher their Defense, the harder this hits.',
    tiered: false,
  },

  // ── Pseudo-skills — not player-selectable; auto-fired by the engine ──────────

  // Counter Strike fires automatically after Brace absorbs a physical hit.
  {
    id: 'counter_strike',
    name: 'Counter Strike',
    family: 'counter_strike',
    rank: 1,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'Auto-executed after Brace absorbs a physical hit. Deals a swift physical counter.',
    tiered: false,
  },

  // Courage Strike Execute fires automatically the turn after Courage Strike is used.
  {
    id: 'courage_strike_execute',
    name: 'Courage Strike',
    family: 'courage_strike',
    rank: 1,
    classRoute: 'strength',
    category: 'offensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'The stored power from Courage Strike unleashes as a massive physical strike.',
    tiered: false,
  },

  // ── Defense Tier 1 — Beefcake ─────────────────────────────────────────────
  {
    id: 'rampart',
    name: 'Rampart',
    family: 'rampart',
    rank: 1,
    classRoute: 'defense',
    category: 'setup',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'self',
    description: 'Creates a temporary HP barrier (~15% max HP) that absorbs incoming damage before real HP is touched. Clears at round end.',
    tiered: true,
  },
  {
    id: 'thick_skin',
    name: 'Thick Skin',
    family: 'thick_skin',
    rank: 1,
    classRoute: 'defense',
    category: 'setup',
    costType: 'flatMP',
    costAmount: 10,
    targeting: 'self',
    description: 'Raises the user\'s Defense by +2 stages for 2 turns.',
    tiered: true,
  },
  {
    id: 'shield_bash',
    name: 'Shield Bash',
    family: 'shield_bash',
    rank: 1,
    classRoute: 'defense',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'single',
    description: 'Deals physical damage and reduces the target\'s Strength by 1 stage for 1 turn.',
    tiered: true,
  },
  {
    id: 'recover',
    name: 'Recover',
    family: 'recover',
    rank: 1,
    classRoute: 'defense',
    category: 'recovery',
    costType: 'flatMP',
    costAmount: 14,
    targeting: 'self',
    description: 'Restores 25% of the user\'s max HP. If Endurance is equipped, bonus HP is added based on missing HP.',
    tiered: true,
  },
  {
    id: 'counter_stance',
    name: 'Counter Stance',
    family: 'counter_stance',
    rank: 1,
    classRoute: 'defense',
    category: 'defensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'User readies a counter stance. If hit by a physical move this turn, damage is halved and a Defense-scaling counter fires automatically. Unlocks Counter Surge.',
    tiered: false,
  },

  // ── Defense Tier 2 — Brolic ───────────────────────────────────────────────
  {
    id: 'taunt',
    name: 'Taunt',
    family: 'taunt',
    rank: 1,
    classRoute: 'defense',
    category: 'utility',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'Forces the target to use an offensive action next turn. Disables Setup, Recovery, and Utility moves for that creature.',
    tiered: false,
  },
  {
    id: 'thick_skin_2',
    name: 'Thick Skin II',
    family: 'thick_skin',
    rank: 2,
    classRoute: 'defense',
    category: 'setup',
    costType: 'flatMP',
    costAmount: 10,
    targeting: 'self',
    description: 'Upgraded Thick Skin. Raises Defense by +2 stages for 3 turns.',
    tiered: true,
  },
  {
    id: 'grit',
    name: 'Grit',
    family: 'grit',
    rank: 1,
    classRoute: 'defense',
    category: 'setup',
    costType: 'percentHP',
    costAmount: 0.08,
    targeting: 'self',
    description: 'Sacrifices 8% current HP to sharply raise Defense by +3 stages for 1 turn.',
    tiered: false,
  },
  {
    id: 'body_check',
    name: 'Body Check',
    family: 'body_check',
    rank: 1,
    classRoute: 'defense',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 14,
    targeting: 'single',
    description: 'Physical attack that uses the user\'s Defense in place of Strength to calculate damage. Rewards a high-Defense build.',
    tiered: false,
  },
  {
    id: 'stand_firm',
    name: 'Stand Firm',
    family: 'stand_firm',
    rank: 1,
    classRoute: 'defense',
    category: 'defensive',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'self',
    description: 'Once per battle: incoming physical damage is halved this turn, and a KO from a single hit is survived at 1 HP.',
    tiered: false,
  },

  // ── Defense Tier 3 — Garrison ─────────────────────────────────────────────
  {
    id: 'retaliation',
    name: 'Retaliation',
    family: 'retaliation',
    rank: 1,
    classRoute: 'defense',
    category: 'defensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'User enters Retaliation stance. Each physical hit received this turn triggers an immediate Defense-scaling counter, up to 3 times.',
    tiered: false,
  },
  {
    id: 'recover_2',
    name: 'Recover II',
    family: 'recover',
    rank: 2,
    classRoute: 'defense',
    category: 'recovery',
    costType: 'flatMP',
    costAmount: 14,
    targeting: 'self',
    description: 'Restores 35% of the user\'s max HP. If Endurance is equipped, bonus HP is added based on missing HP.',
    tiered: true,
  },
  {
    id: 'damage_store',
    name: 'Damage Store',
    family: 'damage_store',
    rank: 1,
    classRoute: 'defense',
    category: 'defensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'Stores all incoming physical damage this turn rather than taking it. At the start of next turn the stored damage lands on the user, then auto-fires a physical strike equal in power to what was stored.',
    tiered: false,
  },
  {
    id: 'meditate',
    name: 'Meditate',
    family: 'meditate',
    rank: 1,
    classRoute: 'defense',
    category: 'recovery',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'User stills completely. Reduces incoming physical damage by 25% this turn and immediately restores 8% of max HP.',
    tiered: false,
  },
  {
    id: 'shield_wall',
    name: 'Shield Wall',
    family: 'shield_wall',
    rank: 1,
    classRoute: 'defense',
    category: 'setup',
    costType: 'flatMP',
    costAmount: 28,
    targeting: 'self',
    description: 'Erects a team-wide barrier that reduces all incoming physical damage to allies by 15% for 2 turns. The user becomes the priority target while active.',
    tiered: false,
  },

  // ── Defense Tier 4 — Vigorous ─────────────────────────────────────────────
  {
    id: 'rampart_2',
    name: 'Rampart II',
    family: 'rampart',
    rank: 2,
    classRoute: 'defense',
    category: 'setup',
    costType: 'flatMP',
    costAmount: 18,
    targeting: 'self',
    description: 'Upgraded Rampart. Creates a larger HP barrier (~25% max HP) that absorbs incoming damage. Clears at round end.',
    tiered: true,
  },
  {
    id: 'shield_bash_2',
    name: 'Shield Bash II',
    family: 'shield_bash',
    rank: 2,
    classRoute: 'defense',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'single',
    description: 'Upgraded Shield Bash. Deals greater physical damage with a guaranteed Strength reduction on the target.',
    tiered: true,
  },
  {
    id: 'last_bastion',
    name: 'Last Bastion',
    family: 'last_bastion',
    rank: 1,
    classRoute: 'defense',
    category: 'setup',
    costType: 'percentHP',
    costAmount: 0.20,
    targeting: 'all_allies',
    description: 'Sacrifices 20% current HP to raise Defense for all active allies by +2 stages for 2 turns.',
    tiered: false,
  },
  {
    id: 'absorb',
    name: 'Absorb',
    family: 'absorb',
    rank: 1,
    classRoute: 'defense',
    category: 'defensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'User intercepts the next physical hit aimed at any ally, taking it instead at 40% reduced damage. If Sacrifice Drive is equipped, the attacker also takes 30% of the absorbed damage.',
    tiered: false,
  },
  {
    id: 'total_defense',
    name: 'Total Defense',
    family: 'total_defense',
    rank: 1,
    classRoute: 'defense',
    category: 'defensive',
    costType: 'flatMP',
    costAmount: 30,
    targeting: 'self',
    description: 'Nullifies all incoming physical damage this turn. Cannot be used in consecutive turns.',
    tiered: false,
  },

  // ── Defense Tier 5 — Aegis ────────────────────────────────────────────────
  {
    id: 'recover_3',
    name: 'Recover III',
    family: 'recover',
    rank: 3,
    classRoute: 'defense',
    category: 'recovery',
    costType: 'flatMP',
    costAmount: 14,
    targeting: 'self',
    description: 'Restores 50% of the user\'s max HP. If Endurance is equipped, bonus HP is added based on missing HP.',
    tiered: true,
  },
  {
    id: 'shield_bash_3',
    name: 'Shield Bash III',
    family: 'shield_bash',
    rank: 3,
    classRoute: 'defense',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'single',
    description: 'Upgraded Shield Bash at maximum power. Guaranteed Strength reduction on the target with the highest base damage of the series.',
    tiered: true,
  },
  {
    id: 'iron_fortress',
    name: 'Iron Fortress',
    family: 'iron_fortress',
    rank: 1,
    classRoute: 'defense',
    category: 'setup',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'Once per battle: permanently raises Defense by +4 stages and increases max HP by 15%.',
    tiered: false,
  },
  {
    id: 'counter_surge',
    name: 'Counter Surge',
    family: 'counter_surge',
    rank: 1,
    classRoute: 'defense',
    category: 'offensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'Only usable after Counter Stance absorbs a hit. Fires a Defense-scaling physical strike amplified by how much damage was absorbed. If Titan\'s Wall is equipped, additional power is added.',
    tiered: false,
  },
  {
    id: 'aegis_shield',
    name: 'Aegis Shield',
    family: 'aegis_shield',
    rank: 1,
    classRoute: 'defense',
    category: 'defensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'The user becomes completely impervious to physical damage this turn. While Aegis Shield is active, Offensive skills and the Attack command are unavailable.',
    tiered: false,
  },

  // ── Defense pseudo-skills — auto-fired by the engine ──────────────────────

  // Counter Stance Counter fires automatically after Counter Stance absorbs a physical hit.
  {
    id: 'counter_stance_counter',
    name: 'Counter Stance Counter',
    family: 'counter_stance_counter',
    rank: 1,
    classRoute: 'defense',
    category: 'offensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'Auto-executed after Counter Stance absorbs a physical hit. A swift Defense-scaling counter strike.',
    tiered: false,
  },

  // Damage Store Strike fires automatically at round start after a Damage Store turn.
  {
    id: 'damage_store_strike',
    name: 'Damage Store Strike',
    family: 'damage_store_strike',
    rank: 1,
    classRoute: 'defense',
    category: 'offensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'Auto-executed at round start after Damage Store. Releases stored energy as a physical strike with power equal to what was absorbed last turn.',
    tiered: false,
  },

  // Retaliation Counter fires once per physical hit received while Retaliation is active.
  {
    id: 'retaliation_counter',
    name: 'Retaliation Counter',
    family: 'retaliation_counter',
    rank: 1,
    classRoute: 'defense',
    category: 'offensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'Auto-executed per physical hit received while Retaliation is active. Defense-scaling counter, up to 3 times per turn.',
    tiered: false,
  },

  // ── Intelligence Tier 1 — Adept ───────────────────────────────────────────
  {
    id: 'mind_spike',
    name: 'Mind Spike',
    family: 'mind_spike',
    rank: 1,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 8,
    targeting: 'single',
    description: 'A sharp bolt of magic energy. Reliable INT-scaling magic damage.',
    tiered: true,
  },
  {
    id: 'focus',
    name: 'Focus',
    family: 'focus',
    rank: 1,
    classRoute: 'intelligence',
    category: 'setup',
    costType: 'flatMP',
    costAmount: 6,
    targeting: 'self',
    description: 'Channel concentration this turn. Raises INT by 2 stages for 2 rounds.',
    tiered: true,
  },
  {
    id: 'reckless_cast',
    name: 'Reckless Cast',
    family: 'reckless_cast',
    rank: 1,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'Unleash raw magic without restraint. High INT-scaling damage but costs HP equal to 10% of damage dealt.',
    tiered: true,
  },
  {
    id: 'mana_surge',
    name: 'Mana Surge',
    family: 'mana_surge',
    rank: 1,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 10,
    targeting: 'single',
    description: 'Magic damage that scales inversely with current MP — hits harder the lower your MP.',
    tiered: true,
  },
  {
    id: 'spell_drain',
    name: 'Spell Drain',
    family: 'spell_drain',
    rank: 1,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 8,
    targeting: 'single',
    description: 'INT-scaling magic strike that restores MP equal to 15% of damage dealt.',
    tiered: false,
  },

  // ── Intelligence Tier 2 — Magician ────────────────────────────────────────
  {
    id: 'mind_spike_2',
    name: 'Mind Spike II',
    family: 'mind_spike',
    rank: 2,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'single',
    description: 'A stronger bolt of magic energy. Reliable INT-scaling magic damage.',
    tiered: true,
  },
  {
    id: 'reckless_cast_2',
    name: 'Reckless Cast II',
    family: 'reckless_cast',
    rank: 2,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'Greater unrestrained magic. Higher INT-scaling damage but costs HP equal to 10% of damage dealt.',
    tiered: true,
  },
  {
    id: 'wild_surge',
    name: 'Wild Surge',
    family: 'wild_surge',
    rank: 1,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 10,
    targeting: 'single',
    description: 'Volatile magic burst with extreme variance. Damage range is twice as wide as normal.',
    tiered: false,
  },
  {
    id: 'mana_burst',
    name: 'Mana Burst',
    family: 'mana_burst',
    rank: 1,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'percentCurrentMP',
    costAmount: 0.25,
    targeting: 'single',
    description: 'Convert raw MP into a magic strike. Costs 25% of current MP; damage scales with the MP spent.',
    tiered: false,
  },
  {
    id: 'channel',
    name: 'Channel',
    family: 'channel',
    rank: 1,
    classRoute: 'intelligence',
    category: 'defensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'Enter a meditative defense stance. Each hit received this turn restores MP equal to 20% of damage taken.',
    tiered: false,
  },

  // ── Intelligence Tier 3 — Wizard ──────────────────────────────────────────
  {
    id: 'focus_2',
    name: 'Focus II',
    family: 'focus',
    rank: 2,
    classRoute: 'intelligence',
    category: 'setup',
    costType: 'flatMP',
    costAmount: 8,
    targeting: 'self',
    description: 'Deeper concentration. Raises INT by 3 stages for 2 rounds.',
    tiered: true,
  },
  {
    id: 'mana_surge_2',
    name: 'Mana Surge II',
    family: 'mana_surge',
    rank: 2,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 14,
    targeting: 'single',
    description: 'Stronger surge scaling inversely with current MP — hits harder the lower your MP.',
    tiered: true,
  },
  {
    id: 'arcane_surge',
    name: 'Arcane Surge',
    family: 'arcane_surge',
    rank: 1,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 16,
    targeting: 'all_enemies',
    description: 'A wave of arcane energy washes over all enemies. INT-scaling magic AoE damage.',
    tiered: true,
  },
  {
    id: 'grand_incantation',
    name: 'Grand Incantation',
    family: 'grand_incantation',
    rank: 1,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 24,
    targeting: 'single',
    description: 'Begin channeling a devastating spell. The incantation fires automatically next turn for massive INT-scaling magic damage.',
    tiered: false,
  },
  {
    id: 'attune',
    name: 'Attune',
    family: 'attune',
    rank: 1,
    classRoute: 'intelligence',
    category: 'setup',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'Harmonize with arcane forces. Your next Art this battle deals +50% damage.',
    tiered: false,
  },

  // ── Intelligence Tier 4 — Sorcerer ────────────────────────────────────────
  {
    id: 'mind_spike_3',
    name: 'Mind Spike III',
    family: 'mind_spike',
    rank: 3,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 16,
    targeting: 'single',
    description: 'A devastating bolt of magic energy. Reliable INT-scaling magic damage.',
    tiered: true,
  },
  {
    id: 'reckless_cast_3',
    name: 'Reckless Cast III',
    family: 'reckless_cast',
    rank: 3,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'Maximum unrestrained magic. Highest INT-scaling damage but costs HP equal to 10% of damage dealt.',
    tiered: true,
  },
  {
    id: 'arcane_surge_2',
    name: 'Arcane Surge II',
    family: 'arcane_surge',
    rank: 2,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 20,
    targeting: 'all_enemies',
    description: 'A stronger wave of arcane energy across all enemies. INT-scaling magic AoE damage.',
    tiered: true,
  },
  {
    id: 'unravel',
    name: 'Unravel',
    family: 'unravel',
    rank: 1,
    classRoute: 'intelligence',
    category: 'utility',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'all_enemies',
    description: 'Erode the magical defenses of all enemies. Lowers all enemies\' Spirit by 1 stage.',
    tiered: false,
  },
  {
    id: 'resonant_cast',
    name: 'Resonant Cast',
    family: 'resonant_cast',
    rank: 1,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 14,
    targeting: 'single',
    description: 'INT-scaling magic strike that deals +30% damage if a magic skill was used last turn.',
    tiered: false,
  },

  // ── Intelligence Tier 5 — Warlock ─────────────────────────────────────────
  {
    id: 'focus_3',
    name: 'Focus III',
    family: 'focus',
    rank: 3,
    classRoute: 'intelligence',
    category: 'setup',
    costType: 'flatMP',
    costAmount: 10,
    targeting: 'self',
    description: 'Peak concentration. Raises INT by 4 stages for 2 rounds.',
    tiered: true,
  },
  {
    id: 'mana_surge_3',
    name: 'Mana Surge III',
    family: 'mana_surge',
    rank: 3,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 18,
    targeting: 'single',
    description: 'Devastating surge scaling inversely with current MP — hits hardest when MP is lowest.',
    tiered: true,
  },
  {
    id: 'arcane_surge_3',
    name: 'Arcane Surge III',
    family: 'arcane_surge',
    rank: 3,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 24,
    targeting: 'all_enemies',
    description: 'The most powerful arcane wave. INT-scaling magic AoE damage hits all enemies.',
    tiered: true,
  },
  {
    id: 'shatter',
    name: 'Shatter',
    family: 'shatter',
    rank: 1,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 18,
    targeting: 'single',
    description: 'Magic strike that scales with the target\'s own Spirit — the more magic resistant the target, the harder it hits.',
    tiered: false,
  },
  {
    id: 'void_strike',
    name: 'Void Strike',
    family: 'void_strike',
    rank: 1,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 28,
    targeting: 'single',
    description: 'Tears through magical resistance entirely. INT-scaling magic damage that completely ignores the target\'s Spirit stat.',
    tiered: false,
  },

  // ── Spirit Tier 1 — Tactician ────────────────────────────────────────────
  {
    id: 'spirit_bolt',
    name: 'Spirit Bolt',
    family: 'spirit_bolt',
    rank: 1,
    classRoute: 'spirit',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 8,
    targeting: 'single',
    description: 'A bolt of spiritual energy. Reliable SPI-scaling magic damage.',
    tiered: true,
  },
  {
    id: 'inner_reserve',
    name: 'Inner Reserve',
    family: 'inner_reserve',
    rank: 1,
    classRoute: 'spirit',
    category: 'recovery',
    costType: 'percentMaxHP',
    costAmount: 0.12,
    targeting: 'self',
    description: 'Sacrifice vitality to restore mana. Costs 12% max HP; restores 15% max MP.',
    tiered: true,
  },
  {
    id: 'ward',
    name: 'Ward',
    family: 'ward',
    rank: 1,
    classRoute: 'spirit',
    category: 'defensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'Priority. Enter a warding stance: take 20% less magic damage this turn and restore 10% of each magic hit as MP.',
    tiered: true,
  },
  {
    id: 'pulse',
    name: 'Pulse',
    family: 'pulse',
    rank: 1,
    classRoute: 'spirit',
    category: 'utility',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'all_enemies',
    description: 'SPI-scaling magic AoE that also lowers all enemies\' Intelligence by 1 stage.',
    tiered: false,
  },
  {
    id: 'clarity_spirit',
    name: 'Clarity',
    family: 'clarity_spirit',
    rank: 1,
    classRoute: 'spirit',
    category: 'recovery',
    costType: 'flatMP',
    costAmount: 8,
    targeting: 'self',
    description: 'Clears all status conditions from self and raises Spirit by 1 stage.',
    tiered: false,
  },

  // ── Spirit Tier 2 — Strategist ────────────────────────────────────────────
  {
    id: 'spirit_bolt_2',
    name: 'Spirit Bolt II',
    family: 'spirit_bolt',
    rank: 2,
    classRoute: 'spirit',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'single',
    description: 'A stronger bolt of spiritual energy. SPI-scaling magic damage.',
    tiered: true,
  },
  {
    id: 'astral_rise',
    name: 'Astral Rise',
    family: 'astral_rise',
    rank: 1,
    classRoute: 'spirit',
    category: 'setup',
    costType: 'flatMP',
    costAmount: 8,
    targeting: 'self',
    description: 'Elevate your spirit. Raises SPI by 2 stages for 2 rounds.',
    tiered: true,
  },
  {
    id: 'mana_siphon',
    name: 'Mana Siphon',
    family: 'mana_siphon',
    rank: 1,
    classRoute: 'spirit',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 10,
    targeting: 'single',
    description: 'SPI-scaling magic damage that drains 25% of damage dealt from the target\'s MP to yours.',
    tiered: false,
  },
  {
    id: 'quicken',
    name: 'Quicken',
    family: 'quicken',
    rank: 1,
    classRoute: 'spirit',
    category: 'cost_breaker',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'Your next Art costs 50% less MP.',
    tiered: false,
  },
  {
    id: 'null_field',
    name: 'Null Field',
    family: 'null_field',
    rank: 1,
    classRoute: 'spirit',
    category: 'utility',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'all_enemies',
    description: 'Erode enemy spellcasting. Lowers all enemies\' Intelligence by 1 stage for 2 rounds.',
    tiered: false,
  },

  // ── Spirit Tier 3 — Rulebender ────────────────────────────────────────────
  {
    id: 'inner_reserve_2',
    name: 'Inner Reserve II',
    family: 'inner_reserve',
    rank: 2,
    classRoute: 'spirit',
    category: 'recovery',
    costType: 'percentMaxHP',
    costAmount: 0.12,
    targeting: 'self',
    description: 'Costs 12% max HP; restores 25% max MP.',
    tiered: true,
  },
  {
    id: 'ward_2',
    name: 'Ward II',
    family: 'ward',
    rank: 2,
    classRoute: 'spirit',
    category: 'defensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'Priority. Take 30% less magic damage this turn, restore 15% of each magic hit as MP, and reflect 20% of magic damage back to the attacker.',
    tiered: true,
  },
  {
    id: 'astral_rise_2',
    name: 'Astral Rise II',
    family: 'astral_rise',
    rank: 2,
    classRoute: 'spirit',
    category: 'setup',
    costType: 'flatMP',
    costAmount: 12,
    targeting: 'self',
    description: 'Raises SPI by 3 stages for 2 rounds.',
    tiered: true,
  },
  {
    id: 'spirit_surge',
    name: 'Spirit Surge',
    family: 'spirit_surge',
    rank: 1,
    classRoute: 'spirit',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 18,
    targeting: 'single',
    description: 'A powerful surge of spiritual force. Large SPI-scaling magic damage.',
    tiered: false,
  },
  {
    id: 'deep_meditation',
    name: 'Deep Meditation',
    family: 'deep_meditation',
    rank: 1,
    classRoute: 'spirit',
    category: 'recovery',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'Priority. Restore 30% max MP now and another 30% at the end of this round.',
    tiered: false,
  },

  // ── Spirit Tier 4 — Rulebreaker ───────────────────────────────────────────
  {
    id: 'spirit_bolt_3',
    name: 'Spirit Bolt III',
    family: 'spirit_bolt',
    rank: 3,
    classRoute: 'spirit',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 16,
    targeting: 'single',
    description: 'A devastating bolt of spiritual energy. SPI-scaling magic damage.',
    tiered: true,
  },
  {
    id: 'soul_rend',
    name: 'Soul Rend',
    family: 'soul_rend',
    rank: 1,
    classRoute: 'spirit',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 14,
    targeting: 'single',
    description: 'SPI-scaling magic damage that steals 1 SPI stage from the target: their SPI drops, yours rises.',
    tiered: false,
  },
  {
    id: 'mana_well',
    name: 'Mana Well',
    family: 'mana_well',
    rank: 1,
    classRoute: 'spirit',
    category: 'recovery',
    costType: 'flatMP',
    costAmount: 18,
    targeting: 'all_allies',
    description: 'Open a wellspring of mana. Restore 20% max MP to all allies.',
    tiered: false,
  },
  {
    id: 'transcendence',
    name: 'Transcendence',
    family: 'transcendence',
    rank: 1,
    classRoute: 'spirit',
    category: 'cost_breaker',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'Your next Art costs 0 MP.',
    tiered: false,
  },
  {
    id: 'arcane_veil',
    name: 'Arcane Veil',
    family: 'arcane_veil',
    rank: 1,
    classRoute: 'spirit',
    category: 'defensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'Priority, once per battle. Take 0 damage from all Arts this turn.',
    tiered: false,
  },

  // ── Spirit Tier 5 — Mastermind ────────────────────────────────────────────
  {
    id: 'inner_reserve_3',
    name: 'Inner Reserve III',
    family: 'inner_reserve',
    rank: 3,
    classRoute: 'spirit',
    category: 'recovery',
    costType: 'percentMaxHP',
    costAmount: 0.10,
    targeting: 'self',
    description: 'Costs 10% max HP; restores 35% max MP.',
    tiered: true,
  },
  {
    id: 'ward_3',
    name: 'Ward III',
    family: 'ward',
    rank: 3,
    classRoute: 'spirit',
    category: 'defensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'self',
    description: 'Priority. Take 40% less magic damage this turn, restore 20% of each magic hit as MP, and reflect 50% of magic damage back to the attacker.',
    tiered: true,
  },
  {
    id: 'astral_rise_3',
    name: 'Astral Rise III',
    family: 'astral_rise',
    rank: 3,
    classRoute: 'spirit',
    category: 'setup',
    costType: 'flatMP',
    costAmount: 16,
    targeting: 'self',
    description: 'Raises SPI by 4 stages for 2 rounds.',
    tiered: true,
  },
  {
    id: 'spirit_collapse',
    name: 'Spirit Collapse',
    family: 'spirit_collapse',
    rank: 1,
    classRoute: 'spirit',
    category: 'offensive',
    costType: 'flatMP',
    costAmount: 24,
    targeting: 'single',
    description: 'SPI-scaling magic damage that also drains 20% of the target\'s current MP and converts it to bonus damage.',
    tiered: false,
  },
  {
    id: 'dominion',
    name: 'Dominion',
    family: 'dominion',
    rank: 1,
    classRoute: 'spirit',
    category: 'utility',
    costType: 'flatMP',
    costAmount: 22,
    targeting: 'all_enemies',
    description: 'Assert magical supremacy. Lower all enemies\' Intelligence and Spirit by 2 stages each. Raise all allies\' Spirit by 2 stages.',
    tiered: false,
  },

  // Grand Incantation auto-fires the turn after Grand Incantation is used.
  {
    id: 'grand_incantation_execute',
    name: 'Grand Incantation',
    family: 'grand_incantation_execute',
    rank: 1,
    classRoute: 'intelligence',
    category: 'offensive',
    costType: 'none',
    costAmount: 0,
    targeting: 'single',
    description: 'Auto-executed the turn after Grand Incantation is used. Massive INT-scaling magic damage.',
    tiered: false,
  },
];

// ── Passive definitions ───────────────────────────────────────────────────────

const CLASS_PASSIVES = [
  // ── Strength Tier 1 — Apprentice ─────────────────────────────────────────
  {
    id: 'heavy_hitter',
    name: 'Heavy Hitter',
    family: 'heavy_hitter',
    rank: 1,
    classRoute: 'strength',
    category: 'damage',
    description: 'Physical damage dealt +5%.',
    tiered: true,
  },
  {
    id: 'thick_muscles',
    name: 'Thick Muscles',
    family: 'thick_muscles',
    rank: 1,
    classRoute: 'strength',
    category: 'stat',
    description: 'Strength +5%.',
    tiered: true,
  },
  {
    id: 'native_strength',
    name: 'Native Strength',
    family: 'native_strength',
    rank: 1,
    classRoute: 'strength',
    category: 'damage',
    description: 'Damage dealt of the creature\'s native element +5%.',
    tiered: true,
  },
  {
    id: 'battle_instinct',
    name: 'Battle Instinct',
    family: 'battle_instinct',
    rank: 1,
    classRoute: 'strength',
    category: 'damage',
    description: 'Critical hit chance on physical moves +3%.',
    tiered: false,
  },
  {
    id: 'berserkers_blood',
    name: 'Berserker\'s Blood',
    family: 'berserkers_blood',
    rank: 1,
    classRoute: 'strength',
    category: 'damage',
    description: 'Physical damage dealt +8% while the user is below 50% HP.',
    tiered: false,
  },

  // ── Strength Tier 2 — Squire ──────────────────────────────────────────────
  {
    id: 'heavy_hitter_2',
    name: 'Heavy Hitter II',
    family: 'heavy_hitter',
    rank: 2,
    classRoute: 'strength',
    category: 'damage',
    description: 'Physical damage dealt +10%.',
    tiered: true,
  },
  {
    id: 'iron_will',
    name: 'Iron Will',
    family: 'iron_will',
    rank: 1,
    classRoute: 'strength',
    category: 'resistance',
    description: 'Damage taken reduced by a small % while the user is below 50% HP.',
    tiered: false,
  },
  {
    id: 'relentless',
    name: 'Relentless',
    family: 'relentless',
    rank: 1,
    classRoute: 'strength',
    category: 'damage',
    description: 'Each consecutive turn the user uses a physical attack, damage dealt increases slightly. Bonus is capped.',
    tiered: false,
  },
  {
    id: 'vital_drain',
    name: 'Vital Drain',
    family: 'vital_drain',
    rank: 1,
    classRoute: 'strength',
    category: 'resource',
    description: 'Power Through restores additional HP equal to a small % of damage dealt.',
    tiered: false,
  },
  {
    id: 'counter_expert',
    name: 'Counter Expert',
    family: 'counter_expert',
    rank: 1,
    classRoute: 'strength',
    category: 'damage',
    description: 'Counter Strike deals bonus physical damage.',
    tiered: false,
  },

  // ── Strength Tier 3 — Knight ──────────────────────────────────────────────
  {
    id: 'thick_muscles_2',
    name: 'Thick Muscles II',
    family: 'thick_muscles',
    rank: 2,
    classRoute: 'strength',
    category: 'stat',
    description: 'Strength +10%.',
    tiered: true,
  },
  {
    id: 'native_strength_2',
    name: 'Native Strength II',
    family: 'native_strength',
    rank: 2,
    classRoute: 'strength',
    category: 'damage',
    description: 'Damage dealt of the creature\'s native element +10%.',
    tiered: true,
  },
  {
    id: 'collateral',
    name: 'Collateral',
    family: 'collateral',
    rank: 1,
    classRoute: 'strength',
    category: 'damage',
    description: 'All AoE moves (Skills and Arts) deal bonus damage.',
    tiered: false,
  },
  {
    id: 'war_hardened',
    name: 'War Hardened',
    family: 'war_hardened',
    rank: 1,
    classRoute: 'strength',
    category: 'utility',
    description: 'The Speed penalty from War Stance is reduced.',
    tiered: false,
  },
  {
    id: 'titans_resolve',
    name: 'Titan\'s Resolve',
    family: 'titans_resolve',
    rank: 1,
    classRoute: 'strength',
    category: 'resistance',
    description: 'Incoming damage is reduced during Courage Strike\'s wind-up turn.',
    tiered: false,
  },

  // ── Strength Tier 4 — Hero ────────────────────────────────────────────────
  {
    id: 'heavy_hitter_3',
    name: 'Heavy Hitter III',
    family: 'heavy_hitter',
    rank: 3,
    classRoute: 'strength',
    category: 'damage',
    description: 'Physical damage dealt +15%.',
    tiered: true,
  },
  {
    id: 'killing_instinct',
    name: 'Killing Instinct',
    family: 'killing_instinct',
    rank: 1,
    classRoute: 'strength',
    category: 'damage',
    description: 'After KO\'ing an enemy, the user\'s next attack this battle deals bonus damage.',
    tiered: false,
  },
  {
    id: 'battle_worn',
    name: 'Battle-Worn',
    family: 'battle_worn',
    rank: 1,
    classRoute: 'strength',
    category: 'stat',
    description: 'Each time the user takes a physical hit, Defense increases slightly for the rest of the battle. Caps at 2–3 stacks.',
    tiered: false,
  },
  {
    id: 'vengeance',
    name: 'Vengeance',
    family: 'vengeance',
    rank: 1,
    classRoute: 'strength',
    category: 'damage',
    description: 'When an ally is KO\'d, the user gains a physical damage boost for 2 turns.',
    tiered: false,
  },
  {
    id: 'indomitable',
    name: 'Indomitable',
    family: 'indomitable',
    rank: 1,
    classRoute: 'strength',
    category: 'utility',
    description: 'Once per battle, if the user would be KO\'d they survive at 1 HP instead.',
    tiered: false,
  },

  // ── Strength Tier 5 — Kingslayer ──────────────────────────────────────────
  {
    id: 'thick_muscles_3',
    name: 'Thick Muscles III',
    family: 'thick_muscles',
    rank: 3,
    classRoute: 'strength',
    category: 'stat',
    description: 'Strength +15%.',
    tiered: true,
  },
  {
    id: 'native_strength_3',
    name: 'Native Strength III',
    family: 'native_strength',
    rank: 3,
    classRoute: 'strength',
    category: 'damage',
    description: 'Damage dealt of the creature\'s native element +15%.',
    tiered: true,
  },
  {
    id: 'fatal_blow',
    name: 'Fatal Blow',
    family: 'fatal_blow',
    rank: 1,
    classRoute: 'strength',
    category: 'damage',
    description: 'Critical hits deal significantly more damage.',
    tiered: false,
  },
  {
    id: 'spite',
    name: 'Spite',
    family: 'spite',
    rank: 1,
    classRoute: 'strength',
    category: 'damage',
    description: 'When the user is hit by a super effective move, their next physical attack deals bonus damage.',
    tiered: false,
  },
  {
    id: 'warlords_presence',
    name: 'Warlord\'s Presence',
    family: 'warlords_presence',
    rank: 1,
    classRoute: 'strength',
    category: 'damage',
    description: 'While this creature is active, all active allies deal slightly more physical damage.',
    tiered: false,
  },

  // ── Defense Tier 1 — Beefcake ─────────────────────────────────────────────
  {
    id: 'thick_skinned',
    name: 'Thick Skinned',
    family: 'thick_skinned',
    rank: 1,
    classRoute: 'defense',
    category: 'stat',
    description: 'Defense +5%.',
    tiered: true,
  },
  {
    id: 'resilient',
    name: 'Resilient',
    family: 'resilient',
    rank: 1,
    classRoute: 'defense',
    category: 'utility',
    description: 'Restores 3% of max HP at the end of each round.',
    tiered: true,
  },
  {
    id: 'thornmail',
    name: 'Thornmail',
    family: 'thornmail',
    rank: 1,
    classRoute: 'defense',
    category: 'resistance',
    description: 'When hit by a physical attack, the attacker takes 8% of the damage dealt back as physical damage.',
    tiered: true,
  },
  {
    id: 'sturdy',
    name: 'Sturdy',
    family: 'sturdy',
    rank: 1,
    classRoute: 'defense',
    category: 'resistance',
    description: 'If a single hit exceeds 25% of the user\'s max HP, that hit is reduced by 12%.',
    tiered: false,
  },
  {
    id: 'counter_force',
    name: 'Counter Force',
    family: 'counter_force',
    rank: 1,
    classRoute: 'defense',
    category: 'damage',
    description: 'Counter Stance Counter deals 30% more damage.',
    tiered: false,
  },

  // ── Defense Tier 2 — Brolic ───────────────────────────────────────────────
  {
    id: 'thick_skinned_2',
    name: 'Thick Skinned II',
    family: 'thick_skinned',
    rank: 2,
    classRoute: 'defense',
    category: 'stat',
    description: 'Defense +10%.',
    tiered: true,
  },
  {
    id: 'pressure_point',
    name: 'Pressure Point',
    family: 'pressure_point',
    rank: 1,
    classRoute: 'defense',
    category: 'utility',
    description: 'When the user takes a physical hit, the attacker\'s Strength is lowered by 1 stage for 1 turn.',
    tiered: false,
  },
  {
    id: 'heavy_frame',
    name: 'Heavy Frame',
    family: 'heavy_frame',
    rank: 1,
    classRoute: 'defense',
    category: 'stat',
    description: 'Max HP +5%.',
    tiered: true,
  },
  {
    id: 'iron_body',
    name: 'Iron Body',
    family: 'iron_body',
    rank: 1,
    classRoute: 'defense',
    category: 'damage',
    description: 'Body Check deals 25% more damage.',
    tiered: false,
  },
  {
    id: 'fortified',
    name: 'Fortified',
    family: 'fortified',
    rank: 1,
    classRoute: 'defense',
    category: 'resistance',
    description: 'Incoming damage reduced by 10% while the user has any positive Defense stages active.',
    tiered: false,
  },

  // ── Defense Tier 3 — Garrison ─────────────────────────────────────────────
  {
    id: 'thick_skinned_3',
    name: 'Thick Skinned III',
    family: 'thick_skinned',
    rank: 3,
    classRoute: 'defense',
    category: 'stat',
    description: 'Defense +15%.',
    tiered: true,
  },
  {
    id: 'endurance',
    name: 'Endurance',
    family: 'endurance',
    rank: 1,
    classRoute: 'defense',
    category: 'utility',
    description: 'Recover skills restore bonus HP proportional to the user\'s missing HP.',
    tiered: false,
  },
  {
    id: 'resilient_2',
    name: 'Resilient II',
    family: 'resilient',
    rank: 2,
    classRoute: 'defense',
    category: 'utility',
    description: 'Restores 6% of max HP at the end of each round.',
    tiered: true,
  },
  {
    id: 'thornmail_2',
    name: 'Thornmail II',
    family: 'thornmail',
    rank: 2,
    classRoute: 'defense',
    category: 'resistance',
    description: 'When hit by a physical attack, the attacker takes 14% of the damage dealt back as physical damage.',
    tiered: true,
  },
  {
    id: 'defenders_aura',
    name: 'Defender\'s Aura',
    family: 'defenders_aura',
    rank: 1,
    classRoute: 'defense',
    category: 'resistance',
    description: 'While this creature is active, all active allies take 8% less physical damage.',
    tiered: false,
  },

  // ── Defense Tier 4 — Vigorous ─────────────────────────────────────────────
  {
    id: 'heavy_frame_2',
    name: 'Heavy Frame II',
    family: 'heavy_frame',
    rank: 2,
    classRoute: 'defense',
    category: 'stat',
    description: 'Max HP +10%.',
    tiered: true,
  },
  {
    id: 'toughness',
    name: 'Toughness',
    family: 'toughness',
    rank: 1,
    classRoute: 'defense',
    category: 'resistance',
    description: 'Each physical hit received grants a stacking −5% incoming damage reduction, up to 3 stacks.',
    tiered: false,
  },
  {
    id: 'thornmail_3',
    name: 'Thornmail III',
    family: 'thornmail',
    rank: 3,
    classRoute: 'defense',
    category: 'resistance',
    description: 'When hit by a physical attack, the attacker takes 20% of the damage dealt back as physical damage.',
    tiered: true,
  },
  {
    id: 'sacrifice_drive',
    name: 'Sacrifice Drive',
    family: 'sacrifice_drive',
    rank: 1,
    classRoute: 'defense',
    category: 'utility',
    description: 'When using Absorb, the attacker takes an additional 30% of the absorbed damage as reflected physical.',
    tiered: false,
  },
  {
    id: 'unassailable',
    name: 'Unassailable',
    family: 'unassailable',
    rank: 1,
    classRoute: 'defense',
    category: 'utility',
    description: 'Once per battle, block a status effect that would be applied to this creature.',
    tiered: false,
  },

  // ── Defense Tier 5 — Aegis ────────────────────────────────────────────────
  {
    id: 'juggernaut',
    name: 'Juggernaut',
    family: 'juggernaut',
    rank: 1,
    classRoute: 'defense',
    category: 'stat',
    description: 'Defense +5% and max HP +5%.',
    tiered: false,
  },
  {
    id: 'indestructible',
    name: 'Indestructible',
    family: 'indestructible',
    rank: 1,
    classRoute: 'defense',
    category: 'resistance',
    description: 'If a single hit drops the user to 25% or below max HP, incoming damage is reduced by 20% for 2 turns.',
    tiered: false,
  },
  {
    id: 'titans_wall',
    name: 'Titan\'s Wall',
    family: 'titans_wall',
    rank: 1,
    classRoute: 'defense',
    category: 'damage',
    description: 'Counter Surge deals bonus damage equal to the total amount absorbed by Counter Stance this battle.',
    tiered: false,
  },
  {
    id: 'siege_breaker',
    name: 'Siege Breaker',
    family: 'siege_breaker',
    rank: 1,
    classRoute: 'defense',
    category: 'resistance',
    description: 'While Total Defense or Aegis Shield is active, super-effective damage is capped to neutral.',
    tiered: false,
  },
  {
    id: 'guardians_presence',
    name: 'Guardian\'s Presence',
    family: 'guardians_presence',
    rank: 1,
    classRoute: 'defense',
    category: 'utility',
    description: 'Once per battle, an ally that would be KO\'d while this creature is alive survives at 1 HP instead.',
    tiered: false,
  },

  // ── Intelligence Tier 1 — Adept ───────────────────────────────────────────
  {
    id: 'sharp_mind',
    name: 'Sharp Mind',
    family: 'sharp_mind',
    rank: 1,
    classRoute: 'intelligence',
    category: 'stat',
    description: 'Intelligence +5%.',
    tiered: true,
  },
  {
    id: 'spell_pressure',
    name: 'Spell Pressure',
    family: 'spell_pressure',
    rank: 1,
    classRoute: 'intelligence',
    category: 'damage',
    description: 'Magic damage dealt +5%.',
    tiered: true,
  },
  {
    id: 'arcane_well',
    name: 'Arcane Well',
    family: 'arcane_well',
    rank: 1,
    classRoute: 'intelligence',
    category: 'resource',
    description: 'Maximum MP +5%.',
    tiered: true,
  },
  {
    id: 'spellcaster',
    name: 'Spellcaster',
    family: 'spellcaster',
    rank: 1,
    classRoute: 'intelligence',
    category: 'damage',
    description: 'Critical hit chance on magic moves +3%.',
    tiered: false,
  },
  {
    id: 'mana_flow',
    name: 'Mana Flow',
    family: 'mana_flow',
    rank: 1,
    classRoute: 'intelligence',
    category: 'resource',
    description: 'Restore a small amount of MP at the end of each round.',
    tiered: false,
  },

  // ── Intelligence Tier 2 — Magician ────────────────────────────────────────
  {
    id: 'sharp_mind_2',
    name: 'Sharp Mind II',
    family: 'sharp_mind',
    rank: 2,
    classRoute: 'intelligence',
    category: 'stat',
    description: 'Intelligence +10%.',
    tiered: true,
  },
  {
    id: 'berserker_mage',
    name: 'Berserker Mage',
    family: 'berserker_mage',
    rank: 1,
    classRoute: 'intelligence',
    category: 'damage',
    description: 'Magic damage dealt +8% when below 50% HP.',
    tiered: false,
  },
  {
    id: 'conduit',
    name: 'Conduit',
    family: 'conduit',
    rank: 1,
    classRoute: 'intelligence',
    category: 'resource',
    description: 'Channel restores additional MP per hit received (restore rate increased by 50%).',
    tiered: false,
  },
  {
    id: 'lingering_power',
    name: 'Lingering Power',
    family: 'lingering_power',
    rank: 1,
    classRoute: 'intelligence',
    category: 'damage',
    description: 'After Focus expires, retain half of the INT bonus for one additional round.',
    tiered: false,
  },
  {
    id: 'overchannel',
    name: 'Overchannel',
    family: 'overchannel',
    rank: 1,
    classRoute: 'intelligence',
    category: 'resource',
    description: 'Reduce the HP recoil on Reckless Cast by half.',
    tiered: false,
  },

  // ── Intelligence Tier 3 — Wizard ──────────────────────────────────────────
  {
    id: 'spell_pressure_2',
    name: 'Spell Pressure II',
    family: 'spell_pressure',
    rank: 2,
    classRoute: 'intelligence',
    category: 'damage',
    description: 'Magic damage dealt +10%.',
    tiered: true,
  },
  {
    id: 'arcane_well_2',
    name: 'Arcane Well II',
    family: 'arcane_well',
    rank: 2,
    classRoute: 'intelligence',
    category: 'resource',
    description: 'Maximum MP +10%.',
    tiered: true,
  },
  {
    id: 'collateral_spell',
    name: 'Collateral Spell',
    family: 'collateral_spell',
    rank: 1,
    classRoute: 'intelligence',
    category: 'damage',
    description: 'AoE magic moves deal +10% damage.',
    tiered: false,
  },
  {
    id: 'concentration',
    name: 'Concentration',
    family: 'concentration',
    rank: 1,
    classRoute: 'intelligence',
    category: 'damage',
    description: 'Magic damage dealt +12% if this creature was not hit last turn.',
    tiered: false,
  },
  {
    id: 'incantation_guard',
    name: 'Incantation Guard',
    family: 'incantation_guard',
    rank: 1,
    classRoute: 'intelligence',
    category: 'resistance',
    description: 'Damage received is reduced by 20% during the Grand Incantation wind-up turn.',
    tiered: false,
  },

  // ── Intelligence Tier 4 — Sorcerer ────────────────────────────────────────
  {
    id: 'sharp_mind_3',
    name: 'Sharp Mind III',
    family: 'sharp_mind',
    rank: 3,
    classRoute: 'intelligence',
    category: 'stat',
    description: 'Intelligence +15%.',
    tiered: true,
  },
  {
    id: 'spell_echo',
    name: 'Spell Echo',
    family: 'spell_echo',
    rank: 1,
    classRoute: 'intelligence',
    category: 'damage',
    description: '20% chance for magic skills to fire a second hit at 40% of original damage.',
    tiered: false,
  },
  {
    id: 'surge_mastery',
    name: 'Surge Mastery',
    family: 'surge_mastery',
    rank: 1,
    classRoute: 'intelligence',
    category: 'damage',
    description: 'Mana Surge\'s low-MP damage bonus is increased by 25%.',
    tiered: false,
  },
  {
    id: 'mana_weaver',
    name: 'Mana Weaver',
    family: 'mana_weaver',
    rank: 1,
    classRoute: 'intelligence',
    category: 'resource',
    description: 'Reduce the MP cost of Mana Burst by 30% (costs 17.5% of current MP instead of 25%).',
    tiered: false,
  },
  {
    id: 'indomitable_mind',
    name: 'Indomitable Mind',
    family: 'indomitable_mind',
    rank: 1,
    classRoute: 'intelligence',
    category: 'utility',
    description: 'Once per battle, survive a KO hit at 1 HP.',
    tiered: false,
  },

  // ── Intelligence Tier 5 — Warlock ─────────────────────────────────────────
  {
    id: 'spell_pressure_3',
    name: 'Spell Pressure III',
    family: 'spell_pressure',
    rank: 3,
    classRoute: 'intelligence',
    category: 'damage',
    description: 'Magic damage dealt +15%.',
    tiered: true,
  },
  {
    id: 'arcane_well_3',
    name: 'Arcane Well III',
    family: 'arcane_well',
    rank: 3,
    classRoute: 'intelligence',
    category: 'resource',
    description: 'Maximum MP +15%.',
    tiered: true,
  },
  {
    id: 'fatal_spell',
    name: 'Fatal Spell',
    family: 'fatal_spell',
    rank: 1,
    classRoute: 'intelligence',
    category: 'damage',
    description: 'Magic critical hits deal 50% additional damage.',
    tiered: false,
  },
  {
    id: 'arcane_dominance',
    name: 'Arcane Dominance',
    family: 'arcane_dominance',
    rank: 1,
    classRoute: 'intelligence',
    category: 'damage',
    description: 'All allies deal +8% magic damage while this creature is active.',
    tiered: false,
  },
  {
    id: 'spellstorm',
    name: 'Spellstorm',
    family: 'spellstorm',
    rank: 1,
    classRoute: 'intelligence',
    category: 'damage',
    description: '25% chance to double damage when targeting a creature below 30% HP.',
    tiered: false,
  },

  // ── Spirit Tier 1 — Tactician ─────────────────────────────────────────────
  {
    id: 'spirit_ward',
    name: 'Spirit Ward',
    family: 'spirit_ward',
    rank: 1,
    classRoute: 'spirit',
    category: 'defense',
    description: 'Ward reduces incoming magic damage by 20% and restores 10% of damage taken as MP.',
    tiered: true,
  },
  {
    id: 'arcane_resilience',
    name: 'Arcane Resilience',
    family: 'arcane_resilience',
    rank: 1,
    classRoute: 'spirit',
    category: 'stat',
    description: 'Spirit +5%.',
    tiered: true,
  },
  {
    id: 'mana_reservoir',
    name: 'Mana Reservoir',
    family: 'mana_reservoir',
    rank: 1,
    classRoute: 'spirit',
    category: 'resource',
    description: 'Maximum MP +8%.',
    tiered: true,
  },
  {
    id: 'art_affinity',
    name: 'Art Affinity',
    family: 'art_affinity',
    rank: 1,
    classRoute: 'spirit',
    category: 'resource',
    description: 'Art MP costs reduced by 10%.',
    tiered: false,
  },
  {
    id: 'still_mind',
    name: 'Still Mind',
    family: 'still_mind',
    rank: 1,
    classRoute: 'spirit',
    category: 'stat',
    description: 'Raises own Spirit by 1 stage at the start of battle.',
    tiered: false,
  },

  // ── Spirit Tier 2 — Strategist ────────────────────────────────────────────
  {
    id: 'spirit_ward_2',
    name: 'Spirit Ward II',
    family: 'spirit_ward',
    rank: 2,
    classRoute: 'spirit',
    category: 'defense',
    description: 'Ward reduces incoming magic damage by 30%, restores 15% of damage as MP, and reflects 20% back to the attacker.',
    tiered: true,
  },
  {
    id: 'arcane_absorption',
    name: 'Arcane Absorption',
    family: 'arcane_absorption',
    rank: 1,
    classRoute: 'spirit',
    category: 'resource',
    description: 'When struck by a magic attack, restore 5% of max MP.',
    tiered: false,
  },
  {
    id: 'mana_discipline',
    name: 'Mana Discipline',
    family: 'mana_discipline',
    rank: 1,
    classRoute: 'spirit',
    category: 'damage',
    description: '+5% Art damage per positive Spirit stage currently active.',
    tiered: false,
  },
  {
    id: 'art_amplify',
    name: 'Art Amplify',
    family: 'art_amplify',
    rank: 1,
    classRoute: 'spirit',
    category: 'damage',
    description: 'Arts deal +8% damage.',
    tiered: false,
  },
  {
    id: 'runic_skin',
    name: 'Runic Skin',
    family: 'runic_skin',
    rank: 1,
    classRoute: 'spirit',
    category: 'defense',
    description: 'Take 5% less damage from all magic attacks.',
    tiered: false,
  },

  // ── Spirit Tier 3 — Rulebender ────────────────────────────────────────────
  {
    id: 'arcane_resilience_2',
    name: 'Arcane Resilience II',
    family: 'arcane_resilience',
    rank: 2,
    classRoute: 'spirit',
    category: 'stat',
    description: 'Spirit +10%.',
    tiered: true,
  },
  {
    id: 'mana_reservoir_2',
    name: 'Mana Reservoir II',
    family: 'mana_reservoir',
    rank: 2,
    classRoute: 'spirit',
    category: 'resource',
    description: 'Maximum MP +12%.',
    tiered: true,
  },
  {
    id: 'trance_mastery',
    name: 'Trance Mastery',
    family: 'trance_mastery',
    rank: 1,
    classRoute: 'spirit',
    category: 'resource',
    description: 'Ward MP restore rate increased by 50%.',
    tiered: false,
  },
  {
    id: 'spirit_flow',
    name: 'Spirit Flow',
    family: 'spirit_flow',
    rank: 1,
    classRoute: 'spirit',
    category: 'resource',
    description: 'After using an Art, restore MP equal to 10% of its cost.',
    tiered: false,
  },
  {
    id: 'replenishing_mind',
    name: 'Replenishing Mind',
    family: 'replenishing_mind',
    rank: 1,
    classRoute: 'spirit',
    category: 'resource',
    description: 'Restore 3% of max MP at the end of each round.',
    tiered: false,
  },

  // ── Spirit Tier 4 — Rulebreaker ────────────────────────────────────────────
  {
    id: 'spirit_ward_3',
    name: 'Spirit Ward III',
    family: 'spirit_ward',
    rank: 3,
    classRoute: 'spirit',
    category: 'defense',
    description: 'Ward reduces incoming magic damage by 40%, restores 20% of damage as MP, and reflects 50% back to the attacker.',
    tiered: true,
  },
  {
    id: 'art_celerity',
    name: 'Art Celerity',
    family: 'art_celerity',
    rank: 1,
    classRoute: 'spirit',
    category: 'resource',
    description: 'Art MP costs reduced by an additional 15% (stacks with Art Affinity).',
    tiered: false,
  },
  {
    id: 'spell_harvest',
    name: 'Spell Harvest',
    family: 'spell_harvest',
    rank: 1,
    classRoute: 'spirit',
    category: 'resource',
    description: 'When an ally is struck by a magic attack, restore 5% of max MP.',
    tiered: false,
  },
  {
    id: 'indomitable_will',
    name: 'Indomitable Will',
    family: 'indomitable_will',
    rank: 1,
    classRoute: 'spirit',
    category: 'survival',
    description: 'Once per battle, survive a knockout at 1 HP and restore 20% of max MP.',
    tiered: false,
  },
  {
    id: 'dominion_aura',
    name: 'Dominion Aura',
    family: 'dominion_aura',
    rank: 1,
    classRoute: 'spirit',
    category: 'defense',
    description: 'All allies take 5% less magic damage while this creature is active.',
    tiered: false,
  },

  // ── Spirit Tier 5 — Mastermind ────────────────────────────────────────────
  {
    id: 'arcane_resilience_3',
    name: 'Arcane Resilience III',
    family: 'arcane_resilience',
    rank: 3,
    classRoute: 'spirit',
    category: 'stat',
    description: 'Spirit +15%.',
    tiered: true,
  },
  {
    id: 'mana_reservoir_3',
    name: 'Mana Reservoir III',
    family: 'mana_reservoir',
    rank: 3,
    classRoute: 'spirit',
    category: 'resource',
    description: 'Maximum MP +16%.',
    tiered: true,
  },
  {
    id: 'spirit_overload',
    name: 'Spirit Overload',
    family: 'spirit_overload',
    rank: 1,
    classRoute: 'spirit',
    category: 'damage',
    description: 'Arts used while Transcendence is active deal +20% damage.',
    tiered: false,
  },
  {
    id: 'art_mastery',
    name: 'Art Mastery',
    family: 'art_mastery',
    rank: 1,
    classRoute: 'spirit',
    category: 'resource',
    description: 'Art MP costs reduced by an additional 10% (stacks with Art Affinity and Art Celerity, total 35%).',
    tiered: false,
  },
  {
    id: 'nullify_presence',
    name: 'Nullify Presence',
    family: 'nullify_presence',
    rank: 1,
    classRoute: 'spirit',
    category: 'support',
    description: 'While this creature is active, allies cannot be inflicted with status conditions.',
    tiered: false,
  },
];

// ── Class route definitions ───────────────────────────────────────────────────

const CLASS_ROUTES = [
  {
    id: 'strength',
    name: 'Strength',
    description: 'Pure physical offense. High damage output, power stacking, and finisher pressure.',
    tiers: [
      {
        tier: 1,
        name: 'Apprentice',
        levelRange: [10, 20],
        skills: ['cleave', 'temper', 'reckless_strike', 'final_strike', 'finishing_blow'],
        passives: ['heavy_hitter', 'thick_muscles', 'native_strength', 'battle_instinct', 'berserkers_blood'],
      },
      {
        tier: 2,
        name: 'Squire',
        levelRange: [20, 30],
        skills: ['cleave_2', 'reckless_strike_2', 'challenge', 'power_through', 'brace'],
        passives: ['heavy_hitter_2', 'iron_will', 'relentless', 'vital_drain', 'counter_expert'],
      },
      {
        tier: 3,
        name: 'Knight',
        levelRange: [30, 40],
        skills: ['temper_2', 'final_strike_2', 'war_stance', 'sweep', 'courage_strike'],
        passives: ['thick_muscles_2', 'native_strength_2', 'collateral', 'war_hardened', 'titans_resolve'],
      },
      {
        tier: 4,
        name: 'Hero',
        levelRange: [40, 50],
        skills: ['cleave_3', 'reckless_strike_3', 'sweep_2', 'rally_cry', 'heroic_surge'],
        passives: ['heavy_hitter_3', 'killing_instinct', 'battle_worn', 'vengeance', 'indomitable'],
      },
      {
        tier: 5,
        name: 'Kingslayer',
        levelRange: [50, 60],
        skills: ['temper_3', 'final_strike_3', 'sweep_3', 'defiant', 'castlebreaker'],
        passives: ['thick_muscles_3', 'native_strength_3', 'fatal_blow', 'spite', 'warlords_presence'],
      },
    ],
  },
  {
    id: 'defense',
    name: 'Defense',
    description: 'Resilient frontliner. Absorbs punishment, punishes aggression, and protects the team.',
    tiers: [
      {
        tier: 1,
        name: 'Beefcake',
        levelRange: [10, 20],
        skills:   ['rampart', 'thick_skin', 'shield_bash', 'recover', 'counter_stance'],
        passives: ['thick_skinned', 'resilient', 'thornmail', 'sturdy', 'counter_force'],
      },
      {
        tier: 2,
        name: 'Brolic',
        levelRange: [20, 30],
        skills:   ['taunt', 'thick_skin_2', 'grit', 'body_check', 'stand_firm'],
        passives: ['thick_skinned_2', 'pressure_point', 'heavy_frame', 'iron_body', 'fortified'],
      },
      {
        tier: 3,
        name: 'Garrison',
        levelRange: [30, 40],
        skills:   ['retaliation', 'recover_2', 'damage_store', 'meditate', 'shield_wall'],
        passives: ['thick_skinned_3', 'endurance', 'resilient_2', 'thornmail_2', 'defenders_aura'],
      },
      {
        tier: 4,
        name: 'Vigorous',
        levelRange: [40, 50],
        skills:   ['rampart_2', 'shield_bash_2', 'last_bastion', 'absorb', 'total_defense'],
        passives: ['heavy_frame_2', 'toughness', 'thornmail_3', 'sacrifice_drive', 'unassailable'],
      },
      {
        tier: 5,
        name: 'Aegis',
        levelRange: [50, 60],
        skills:   ['recover_3', 'shield_bash_3', 'iron_fortress', 'counter_surge', 'aegis_shield'],
        passives: ['juggernaut', 'indestructible', 'titans_wall', 'siege_breaker', 'guardians_presence'],
      },
    ],
  },
  {
    id: 'intelligence',
    name: 'Intelligence',
    description: 'Pure magic offense. Intelligence scales magic damage output the same way Strength scales physical. The Mage stacks INT, manages MP as a strategic resource, and applies relentless magic pressure. Uniquely, this route synergizes with the creature\'s native Arts — the only route that makes Arts better.',
    tiers: [
      {
        tier: 1,
        name: 'Adept',
        levelRange: [10, 20],
        skills:   ['mind_spike', 'focus', 'reckless_cast', 'mana_surge', 'spell_drain'],
        passives: ['sharp_mind', 'spell_pressure', 'arcane_well', 'spellcaster', 'mana_flow'],
      },
      {
        tier: 2,
        name: 'Magician',
        levelRange: [20, 30],
        skills:   ['mind_spike_2', 'reckless_cast_2', 'wild_surge', 'mana_burst', 'channel'],
        passives: ['sharp_mind_2', 'berserker_mage', 'conduit', 'lingering_power', 'overchannel'],
      },
      {
        tier: 3,
        name: 'Wizard',
        levelRange: [30, 40],
        skills:   ['focus_2', 'mana_surge_2', 'arcane_surge', 'grand_incantation', 'attune'],
        passives: ['spell_pressure_2', 'arcane_well_2', 'collateral_spell', 'concentration', 'incantation_guard'],
      },
      {
        tier: 4,
        name: 'Sorcerer',
        levelRange: [40, 50],
        skills:   ['mind_spike_3', 'reckless_cast_3', 'arcane_surge_2', 'unravel', 'resonant_cast'],
        passives: ['sharp_mind_3', 'spell_echo', 'surge_mastery', 'mana_weaver', 'indomitable_mind'],
      },
      {
        tier: 5,
        name: 'Warlock',
        levelRange: [50, 60],
        skills:   ['focus_3', 'mana_surge_3', 'arcane_surge_3', 'shatter', 'void_strike'],
        passives: ['spell_pressure_3', 'arcane_well_3', 'fatal_spell', 'arcane_dominance', 'spellstorm'],
      },
    ],
  },
  {
    id: 'spirit',
    name: 'Spirit',
    description: 'Magic defense, MP management, and Art empowerment. Spirit scales magic defense the same way Defense scales physical. The Spirit user blocks and redirects magic pressure, sustains MP across long fights, and amplifies the whole team\'s Art economy. Uniquely, this route makes using Arts cheaper and more powerful.',
    tiers: [
      {
        tier: 1,
        name: 'Tactician',
        levelRange: [10, 20],
        skills:   ['spirit_bolt', 'inner_reserve', 'ward', 'pulse', 'clarity_spirit'],
        passives: ['spirit_ward', 'arcane_resilience', 'mana_reservoir', 'art_affinity', 'still_mind'],
      },
      {
        tier: 2,
        name: 'Strategist',
        levelRange: [20, 30],
        skills:   ['spirit_bolt_2', 'astral_rise', 'mana_siphon', 'quicken', 'null_field'],
        passives: ['spirit_ward_2', 'arcane_absorption', 'mana_discipline', 'art_amplify', 'runic_skin'],
      },
      {
        tier: 3,
        name: 'Rulebender',
        levelRange: [30, 40],
        skills:   ['inner_reserve_2', 'ward_2', 'astral_rise_2', 'spirit_surge', 'deep_meditation'],
        passives: ['arcane_resilience_2', 'mana_reservoir_2', 'trance_mastery', 'spirit_flow', 'replenishing_mind'],
      },
      {
        tier: 4,
        name: 'Rulebreaker',
        levelRange: [40, 50],
        skills:   ['spirit_bolt_3', 'soul_rend', 'mana_well', 'transcendence', 'arcane_veil'],
        passives: ['spirit_ward_3', 'art_celerity', 'spell_harvest', 'indomitable_will', 'dominion_aura'],
      },
      {
        tier: 5,
        name: 'Mastermind',
        levelRange: [50, 60],
        skills:   ['inner_reserve_3', 'ward_3', 'astral_rise_3', 'spirit_collapse', 'dominion'],
        passives: ['arcane_resilience_3', 'mana_reservoir_3', 'spirit_overload', 'art_mastery', 'nullify_presence'],
      },
    ],
  },
  // Other routes are added here as they are scoped in CLASS_SKILLS_AND_PASSIVES_CANON.md.
];

// ── Route stubs — all 16 routes for browse display ───────────────────────────
// Routes with a full CLASS_ROUTES entry are playable; others show as Coming Soon.

const ROUTE_STUBS = [
  { id: 'strength',              name: 'Strength',              tiers: ['Apprentice','Squire','Knight','Hero','Kingslayer'] },
  { id: 'defense',               name: 'Defense',               tiers: ['Beefcake','Brolic','Garrison','Vigorous','Aegis'] },
  { id: 'intelligence',          name: 'Intelligence',          tiers: ['Adept','Magician','Wizard','Sorcerer','Warlock'] },
  { id: 'spirit',                name: 'Spirit',                tiers: ['Tactician','Strategist','Rulebender','Rulebreaker','Mastermind'] },
  { id: 'speed',                 name: 'Speed',                 tiers: ['Scout','Strider','Acrobat','Phantom','Timebreaker'] },
  { id: 'strength_defense',      name: 'Strength / Defense',    tiers: ['Bruiser','Brawler','Combatant','Duelist','Barbarian'] },
  { id: 'strength_intelligence', name: 'Strength / Intelligence',tiers: ['Prodigy','Protagonist','Paladin','Defender','White Knight'] },
  { id: 'strength_spirit',       name: 'Strength / Spirit',     tiers: ['Guard','Resistor','Warder','Blessing','Manna'] },
  { id: 'strength_speed',        name: 'Strength / Speed',      tiers: ['Scrapper','Skirmisher','Ravager','Blitzer','Stormbreaker'] },
  { id: 'defense_intelligence',  name: 'Defense / Intelligence', tiers: ['Opportunist','Calculator','Conductor','Manipulator','Chameleon'] },
  { id: 'defense_spirit',        name: 'Defense / Spirit',      tiers: ['Protector','Frontliner','Tank','Sentry','Fortress'] },
  { id: 'defense_speed',         name: 'Defense / Speed',       tiers: ['Lookout','Keeper','Interceptor','Bulwark','Iron Mirage'] },
  { id: 'intelligence_spirit',   name: 'Intelligence / Spirit', tiers: ['Anointed','Healer','Priest','Holy','Angel'] },
  { id: 'intelligence_speed',    name: 'Intelligence / Speed',  tiers: ['Spark','Analyst','Savant','Chronist','Spellweaver'] },
  { id: 'spirit_speed',          name: 'Spirit / Speed',        tiers: ['Seeker','Pilgrim','Oracle','Ethereal','Ascendant'] },
  { id: 'no_allocation',         name: 'No Manual Allocation',  tiers: ['Thrill-Seeker','Daredevil','Challenger','Contender','Legend'] },
];

// ── Lookup helpers ────────────────────────────────────────────────────────────

function getClassRoute(routeId) {
  return CLASS_ROUTES.find(r => r.id === routeId) || null;
}

function getClassSkill(skillId) {
  return CLASS_SKILLS.find(s => s.id === skillId) || null;
}

function getClassPassive(passiveId) {
  return CLASS_PASSIVES.find(p => p.id === passiveId) || null;
}

function getRouteStub(routeId) {
  return ROUTE_STUBS.find(r => r.id === routeId) || null;
}
