import {
  HASBEEN_HEROES_FAT_TYPES,
  NOT_MY_KING_ENEMY_TYPES,
  SHOWDOWN_FAT_TYPES,
} from "./campaignConstants.js";

const flagsFor = (types) => Object.fromEntries(types.map((type) => [type, false]));

/**
 * Creates mutable, match-scoped presentation and objective bookkeeping.
 * This state intentionally lives outside the deterministic battle state: it tracks
 * one-time dialogue and grading observations, never combat rules.
 */
export function createCampaignMeta() {
  return {
    clodWarningShown: false,
    clodChargeUsed: false,
    clodChargeHitCount: 0,
    chargeDefended: false,
    statusWarningShown: false,
    summonWarningShown: false,
    rageWarningShown: false,
    cleanseUsed: false,
    spreadHitCount: 0,
    fireWarningShown: false,
    blockedShotWarningShown: false,
    blockedShotQueued: false,
    ghoulWarningShown: false,
    witchDoctorRageWarningShown: false,
    ghoulsDefeatedCount: 0,
    fireDamageTakenCount: 0,
    ghoulBiteTakenCount: 0,
    blackDeathDanceUsed: false,
    witchDoctorHealCastCount: 0,
    fatherTimeRageWarningShown: false,
    archerDefeatedBeforeFatherTime: false,
    archerBlinded: false,
    rewindUsed: false,
    virusPoisonWarningShown: false,
    virusEnemyStatusTauntShown: false,
    playerAfflictedEnemyStatus: false,
    paladinLightseekerWarningShown: false,
    paladinStatusTauntShown: false,
    paladinRageWarningShown: false,
    paladinLightseekerDamageTakenCount: 0,
    paladinStatusAttempted: false,
    paladinDefeatDialogueShown: false,
    monkFakeKilledBeforeReal: false,
    monkBlindAttempted: false,
    gargoyleRageWarningShown: false,
    gargoyleEnteredRage: false,
    gargoylePyroclasmDamageTakenCount: 0,
    sniperFireWarningShown: false,
    wallDestroyedCount: 0,
    sniperBlinded: false,
    minerBlastingCapSplashWarningShown: false,
    minerRageWarningShown: false,
    minerBlastingCapSplashTakenCount: 0,
    minerEnteredRage: false,
    minerRageHarvested: false,
    minerDefeatDialogueShown: false,
    flamethrowerBothHitCount: 0,
    brothersEnteredRage: false,
    brothersDefeatDialogueShown: false,
    brothersRageWarned: flagsFor(["big-brother", "little-brother"]),
    fartDisplacementDamageTakenCount: 0,
    hasbeenDefeatDialogueShown: false,
    hasbeenFatRageWarned: flagsFor(HASBEEN_HEROES_FAT_TYPES),
    roninBlindWarningShown: false,
    roninRageWarningShown: false,
    roninBlindApplied: false,
    roninEnteredRage: false,
    wrongPlacePlayerStunned: false,
    wrongPlaceNukedAllEnemies: false,
    angelRageWarningShown: false,
    angelDefeatedBeforePaladin: false,
    outOfRetirementDefeatDialogueShown: false,
    voidwoodDarkBombDamageTakenCount: 0,
    playerMagicDamageDealtCount: 0,
    voidwoodFallLinesShown: {},
    voidwoodDefeatDialogueShown: false,
    motherNatureGreatFloodUsed: false,
    motherNatureGreatFloodDialogueShown: false,
    spiritWoodsTreantPoisonAttempted: false,
    spiritWoodsTreantPoisonTauntShown: false,
    spiritWoodsPaladinStatusTauntShown: false,
    spiritWoodsTreantFireHit: false,
    spiritWoodsTreantFireTauntShown: false,
    showdownAnyUnitEnteredRage: false,
    showdownFootworkHitAllEnemies: false,
    showdownDefeatDialogueShown: false,
    showdownFatRageWarned: flagsFor(SHOWDOWN_FAT_TYPES),
    notMyKingEnemyEnteredRage: false,
    notMyKingDefeatDialogueShown: false,
    notMyKingEnemyRageWarned: flagsFor(NOT_MY_KING_ENEMY_TYPES),
    voidCastleNemesisEnteredRage: false,
    voidCastleNemesisRageWarningShown: false,
    voidCastleDecoyKilled: false,
    voidCastleSplitShown: false,
    voidCastleDefeatDialogueShown: false,
    finalBattleStageShown: {},
    finalBattleReachWarningShown: false,
    finalBattleRageWarningShown: false,
    finalBattleBanished: false,
    finalBattleBanishDialogueShown: false,
    finalBattleDefeatDialogueShown: false,
  };
}
