alter table player_profiles
  add column if not exists profile_name text not null default '',
  add column if not exists real_name text not null default '',
  add column if not exists bio text not null default '',
  add column if not exists tagline text not null default '',
  add column if not exists avatar_asset_id text not null default '',
  add column if not exists background_image_url text not null default '',
  add column if not exists presence text not null default 'offline',
  add column if not exists favorite_game_slug text not null default '',
  add column if not exists ladder_placements jsonb not null default '[]'::jsonb,
  add column if not exists friends_preview jsonb not null default '[]'::jsonb,
  add column if not exists main_squeeze jsonb,
  add column if not exists badge_ids jsonb not null default '[]'::jsonb,
  add column if not exists favorites jsonb not null default '[]'::jsonb,
  add column if not exists friends jsonb not null default '[]'::jsonb,
  add column if not exists recent_partners jsonb not null default '[]'::jsonb,
  add column if not exists links jsonb not null default '[]'::jsonb,
  add column if not exists preferences jsonb not null default '{}'::jsonb,
  add column if not exists featured_games jsonb not null default '[]'::jsonb,
  add column if not exists recent_activity jsonb not null default '[]'::jsonb,
  add column if not exists thought_count integer not null default 0;

alter table player_metrics
  add column if not exists profile_view_count integer not null default 0,
  add column if not exists thought_post_count integer not null default 0,
  add column if not exists activity_item_count integer not null default 0,
  add column if not exists received_reaction_count integer not null default 0,
  add column if not exists received_comment_count integer not null default 0,
  add column if not exists received_share_count integer not null default 0,
  add column if not exists most_played_game_slug text not null default '',
  add column if not exists most_played_with_player_id text not null default '',
  add column if not exists friend_count integer not null default 0,
  add column if not exists friend_points jsonb not null default '{}'::jsonb,
  add column if not exists total_play_session_count integer not null default 0,
  add column if not exists total_play_time_minutes integer not null default 0,
  add column if not exists unique_games_played_count integer not null default 0,
  add column if not exists event_participation_count integer not null default 0,
  add column if not exists top_three_finish_count integer not null default 0,
  add column if not exists mutual_friend_count integer not null default 0,
  add column if not exists shared_game_count integer not null default 0,
  add column if not exists shared_session_count integer not null default 0,
  add column if not exists shared_event_count integer not null default 0,
  add column if not exists results_screen_profile_open_count integer not null default 0,
  add column if not exists results_screen_add_friend_click_count integer not null default 0,
  add column if not exists chat_profile_open_count integer not null default 0,
  add column if not exists friend_request_sent_count integer not null default 0,
  add column if not exists friend_request_accepted_count integer not null default 0,
  add column if not exists thought_impression_count integer not null default 0,
  add column if not exists profile_open_source_breakdown jsonb not null default '{}'::jsonb;

alter table player_relationships
  add column if not exists main_squeeze_mode text not null default 'manual',
  add column if not exists main_squeeze_player_id text not null default '',
  add column if not exists friend_rail_mode text not null default 'auto',
  add column if not exists manual_friend_slot_player_ids jsonb not null default '[]'::jsonb,
  add column if not exists most_played_with_player_id text not null default '',
  add column if not exists last_played_with_player_id text not null default '',
  add column if not exists recently_played_with_player_ids jsonb not null default '[]'::jsonb,
  add column if not exists friend_player_ids jsonb not null default '[]'::jsonb,
  add column if not exists friend_points_by_player_id jsonb not null default '{}'::jsonb,
  add column if not exists mutual_friend_count_by_player_id jsonb not null default '{}'::jsonb,
  add column if not exists shared_game_count_by_player_id jsonb not null default '{}'::jsonb,
  add column if not exists shared_session_count_by_player_id jsonb not null default '{}'::jsonb,
  add column if not exists shared_event_count_by_player_id jsonb not null default '{}'::jsonb,
  add column if not exists last_shared_session_at_by_player_id jsonb not null default '{}'::jsonb,
  add column if not exists last_shared_event_at_by_player_id jsonb not null default '{}'::jsonb,
  add column if not exists last_interaction_at_by_player_id jsonb not null default '{}'::jsonb;
