import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  REQUIRED_BIO_FIELDS,
  buildCharacterCatalog,
  parseCharacterBio,
  renderCharacterCatalogModule,
} from "./tools/build-character-catalog.mjs";

const root = path.dirname(fileURLToPath(import.meta.url));

test("parses the editorial Markdown format without leaking labels into values", () => {
  const bio = parseCharacterBio(`# Test Bowler

**Age**  
24

**Hometown**  
Test City

**Occupation**  
Lane tester

**Bowling Style**  
Straight and steady.

**Favorite Ball**  
Yam Red

**Personality**  
Focused and kind.

**Bio**  
First paragraph.

Second paragraph.
`, "test-bowler");

  assert.deepEqual(Object.keys(bio), ["slug", "name", ...REQUIRED_BIO_FIELDS]);
  assert.equal(bio.slug, "test-bowler");
  assert.equal(bio.name, "Test Bowler");
  assert.equal(bio.bowlingStyle, "Straight and steady.");
  assert.equal(bio.bio, "First paragraph.\n\nSecond paragraph.");
});

test("builds exactly one complete biography for every canon bowler", () => {
  const catalog = buildCharacterCatalog({
    biosDirectory: path.join(root, "assets", "characters", "character-bios"),
  });

  assert.equal(catalog.length, 30);
  assert.equal(new Set(catalog.map(({ slug }) => slug)).size, 30);
  for (const entry of catalog) {
    assert.ok(entry.name);
    for (const field of REQUIRED_BIO_FIELDS) assert.ok(entry[field], `${entry.slug} is missing ${field}`);
  }
});

test("rejects unknown biography files instead of silently publishing them", () => {
  const temporaryDirectory = fs.mkdtempSync(path.join(os.tmpdir(), "yam-bios-"));
  const sample = fs.readFileSync(
    path.join(root, "assets", "characters", "character-bios", "daisy-monroe.md"),
    "utf8",
  );
  fs.writeFileSync(path.join(temporaryDirectory, "daisy-monroe.md"), sample);
  fs.writeFileSync(path.join(temporaryDirectory, "unknown-bowler.md"), sample.replace("Daisy Monroe", "Unknown Bowler"));

  assert.throws(
    () => buildCharacterCatalog({
      biosDirectory: temporaryDirectory,
      roster: [{ name: "Daisy Monroe", slug: "daisy-monroe" }],
    }),
    /unknown biography/i,
  );
});

test("renders deterministic dependency-free browser data", () => {
  const catalog = [{
    slug: "test-bowler",
    name: "Test Bowler",
    age: "24",
    hometown: "Test City",
    occupation: "Lane tester",
    bowlingStyle: "Straight and steady.",
    favoriteBall: "Yam Red",
    personality: "Focused and kind.",
    bio: "A complete bio.",
  }];

  const rendered = renderCharacterCatalogModule(catalog);
  assert.match(rendered, /Generated by tools\/build-character-catalog\.mjs/);
  assert.match(rendered, /root\.YamCharacterCatalogData = catalog/);
  assert.doesNotMatch(rendered, /require\(|import\s/);
  assert.equal(rendered, renderCharacterCatalogModule(catalog));
});
