// Writes every generated crop's four stage GLBs into farm/assets/crops/ and a
// candidates.json manifest the Crop Lab viewer reads.
//
//   node farm/crop-lab/generator/generate.mjs            # all crops
//   node farm/crop-lab/generator/generate.mjs corn tomato # just these
//
// Deterministic: each model is seeded by "<id>:<stage>", so re-running only
// changes files whose recipe changed.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { MeshBuilder, readTemplate, seeded, writeGLB } from "./mesh-kit.mjs";
import { GENERATED_CROPS, stageFile } from "./crops.mjs";

const CROP_DIR = fileURLToPath(new URL("../../assets/crops/", import.meta.url));
const MANIFEST = fileURLToPath(new URL("../candidates.json", import.meta.url));
const template = readTemplate(readFileSync(`${CROP_DIR}Crop_Carrot_01.glb`));
const only = new Set(process.argv.slice(2));

const manifest = [];
for (const crop of GENERATED_CROPS) {
  const models = [0, 1, 2, 3].map((stage) => stageFile(crop.title, stage));
  manifest.push({ id: crop.id, title: crop.title, models, proposal: crop.proposal });
  if (only.size && !only.has(crop.id)) continue;
  const report = [];
  for (let stage = 0; stage < 4; stage++) {
    const builder = new MeshBuilder();
    crop.draw(builder, seeded(`${crop.id}:${stage}`), stage);
    const name = models[stage].replace(/\.glb$/, "");
    const glb = writeGLB(builder, name, template);
    writeFileSync(`${CROP_DIR}${models[stage]}`, glb);
    report.push(`${builder.triangleCount} tris`);
  }
  console.log(`${crop.title.padEnd(11)} ${report.join(" / ")}`);
}
writeFileSync(MANIFEST, `${JSON.stringify({ note: "Generated by farm/crop-lab/generator/generate.mjs. Candidates are not in the farm catalog until added to js/farm-crops.mts.", crops: manifest }, null, 2)}\n`);
