export const COMPOSITION_GRID_COLUMNS = 12;
export const COMPOSITION_GRID_ROWS = 17;
export const CUSTOM_TITLE_PREFIX = "customTitle_";

export const CUSTOM_TITLE_ELEMENT_DEF = {
  label: "Custom Title Bubble",
  category: "custom",
  type: "title",
  defaultEnabled: true,
  defaultText: "New Section",
  defaultX: 4,
  defaultY: 1,
  defaultW: 2.4,
  defaultH: 0.55,
  minW: 0.75,
  minH: 0.4,
  maxW: 12,
  maxH: 17,
  custom: true,
};

function buildGalleryPhotoElements() {
  return Object.fromEntries(Array.from({ length: 8 }, (_, index) => {
    const slot = index + 1;
    const col = index % 8;
    return [`galleryPhoto${slot}`, {
      label: `Gallery Photo ${slot}`,
      category: "gallery",
      type: "galleryPhoto",
      defaultEnabled: false,
      defaultX: 4.35 + col * 0.42,
      defaultY: 7.85,
      defaultW: 0.4,
      defaultH: 0.62,
      minW: 0.25,
      minH: 0.25,
      maxW: 12,
      maxH: 17,
      photoIndex: index,
    }];
  }));
}

export const PROFILE_COMPOSITION_ELEMENT_REGISTRY = {
  heroSurface: {
    label: "Hero Surface",
    category: "hero",
    type: "surface",
    defaultEnabled: true,
    defaultX: 0,
    defaultY: 0,
    defaultW: 4,
    defaultH: 5,
    minW: 1,
    minH: 1,
    maxW: 12,
    maxH: 17,
  },
  heroPortrait: {
    label: "Portrait Chip",
    category: "hero",
    type: "portrait",
    defaultEnabled: true,
    defaultX: 1,
    defaultY: 0.25,
    defaultW: 2,
    defaultH: 1.8,
    minW: 0.75,
    minH: 0.75,
    maxW: 12,
    maxH: 17,
  },
  heroMetrics: {
    label: "Metrics Chip",
    category: "hero",
    type: "metrics",
    defaultEnabled: true,
    defaultX: 0.8,
    defaultY: 2.3,
    defaultW: 2.4,
    defaultH: 2.4,
    minW: 1,
    minH: 1,
    maxW: 12,
    maxH: 17,
  },
  heroTitle: {
    label: "Hero Title Bubble",
    category: "hero",
    type: "title",
    defaultEnabled: false,
    defaultText: "Player Profile",
    defaultX: 0.8,
    defaultY: 0.2,
    defaultW: 2.4,
    defaultH: 0.55,
    minW: 0.75,
    minH: 0.4,
    maxW: 12,
    maxH: 17,
  },
  identitySurface: {
    label: "Identity Surface",
    category: "identity",
    type: "surface",
    defaultEnabled: false,
    defaultX: 0,
    defaultY: 5,
    defaultW: 4,
    defaultH: 5,
    minW: 1,
    minH: 1,
    maxW: 12,
    maxH: 17,
  },
  identityTitle: {
    label: "Identity Title Bubble",
    category: "identity",
    type: "title",
    defaultEnabled: false,
    defaultText: "Player Profile",
    defaultX: 0.8,
    defaultY: 5.15,
    defaultW: 2.4,
    defaultH: 0.5,
    minW: 0.75,
    minH: 0.4,
    maxW: 12,
    maxH: 17,
  },
  identityName: {
    label: "Name Field",
    category: "identity",
    type: "identityField",
    defaultEnabled: false,
    defaultX: 0.35,
    defaultY: 5.85,
    defaultW: 3.3,
    defaultH: 0.8,
    minW: 1,
    minH: 0.45,
    maxW: 12,
    maxH: 17,
  },
  identityPageViews: {
    label: "Page Views Field",
    category: "identity",
    type: "identityField",
    defaultEnabled: false,
    defaultX: 0.35,
    defaultY: 6.8,
    defaultW: 3.3,
    defaultH: 0.8,
    minW: 1,
    minH: 0.45,
    maxW: 12,
    maxH: 17,
  },
  identityFactoryId: {
    label: "Factory ID Field",
    category: "identity",
    type: "identityField",
    defaultEnabled: false,
    defaultX: 0.35,
    defaultY: 7.75,
    defaultW: 3.3,
    defaultH: 0.8,
    minW: 1,
    minH: 0.45,
    maxW: 12,
    maxH: 17,
  },
  identitySocialLinks: {
    label: "Social Links Field",
    category: "identity",
    type: "identityField",
    defaultEnabled: false,
    defaultX: 0.35,
    defaultY: 8.7,
    defaultW: 3.3,
    defaultH: 1.1,
    minW: 1,
    minH: 0.55,
    maxW: 12,
    maxH: 17,
  },
  identityFriendAction: {
    label: "Friend Action",
    category: "identity",
    type: "playerAction",
    defaultEnabled: false,
    defaultX: 0.35,
    defaultY: 9.95,
    defaultW: 3.3,
    defaultH: 0.55,
    minW: 1,
    minH: 0.35,
    maxW: 12,
    maxH: 17,
  },
  identityMessageAction: {
    label: "Message Action",
    category: "identity",
    type: "playerAction",
    defaultEnabled: false,
    defaultX: 0.35,
    defaultY: 10.65,
    defaultW: 3.3,
    defaultH: 0.55,
    minW: 1,
    minH: 0.35,
    maxW: 12,
    maxH: 17,
  },
  identityGestureActions: {
    label: "Gesture Actions",
    category: "identity",
    type: "playerAction",
    defaultEnabled: false,
    defaultX: 0.35,
    defaultY: 11.35,
    defaultW: 3.3,
    defaultH: 1.1,
    minW: 1,
    minH: 0.55,
    maxW: 12,
    maxH: 17,
  },
  aboutSurface: {
    label: "About Surface",
    category: "about",
    type: "surface",
    defaultEnabled: true,
    defaultX: 8,
    defaultY: 0,
    defaultW: 4,
    defaultH: 2,
    minW: 1,
    minH: 1,
    maxW: 12,
    maxH: 17,
  },
  aboutTitle: {
    label: "About Title Bubble",
    category: "about",
    type: "title",
    defaultEnabled: true,
    defaultText: "About Me",
    defaultX: 8.8,
    defaultY: 0.15,
    defaultW: 2.4,
    defaultH: 0.5,
    minW: 0.75,
    minH: 0.4,
    maxW: 12,
    maxH: 17,
  },
  aboutText: {
    label: "About Text Box",
    category: "about",
    type: "text",
    defaultEnabled: true,
    defaultX: 8.35,
    defaultY: 0.7,
    defaultW: 3.3,
    defaultH: 1.1,
    minW: 0.75,
    minH: 0.45,
    maxW: 12,
    maxH: 17,
  },
  badgesSurface: {
    label: "Badges Surface",
    category: "badges",
    type: "surface",
    defaultEnabled: true,
    defaultX: 8,
    defaultY: 2,
    defaultW: 4,
    defaultH: 2,
    minW: 1,
    minH: 1,
    maxW: 12,
    maxH: 17,
  },
  badgesTitle: {
    label: "Badges Title Bubble",
    category: "badges",
    type: "title",
    defaultEnabled: true,
    defaultText: "Badges",
    defaultX: 8.8,
    defaultY: 2.15,
    defaultW: 2.4,
    defaultH: 0.5,
    minW: 0.75,
    minH: 0.4,
    maxW: 12,
    maxH: 17,
  },
  badgesContent: {
    label: "Badges Content Box",
    category: "badges",
    type: "badges",
    defaultEnabled: true,
    defaultX: 8.35,
    defaultY: 2.7,
    defaultW: 3.3,
    defaultH: 1.1,
    minW: 0.75,
    minH: 0.45,
    maxW: 12,
    maxH: 17,
  },
  friendCodeSurface: {
    label: "Friend Code Surface",
    category: "friendCode",
    type: "surface",
    defaultEnabled: true,
    defaultX: 4,
    defaultY: 7,
    defaultW: 4,
    defaultH: 3,
    minW: 1,
    minH: 1,
    maxW: 12,
    maxH: 17,
  },
  friendCodeTitle: {
    label: "Friend Code Title Bubble",
    category: "friendCode",
    type: "title",
    defaultEnabled: true,
    defaultText: "Friend Code",
    defaultX: 4.8,
    defaultY: 7.15,
    defaultW: 2.4,
    defaultH: 0.5,
    minW: 0.75,
    minH: 0.4,
    maxW: 12,
    maxH: 17,
  },
  friendCodeContent: {
    label: "Friend Code Box",
    category: "friendCode",
    type: "friendCode",
    defaultEnabled: true,
    defaultX: 4.35,
    defaultY: 7.75,
    defaultW: 3.3,
    defaultH: 1.95,
    minW: 1,
    minH: 0.75,
    maxW: 12,
    maxH: 17,
  },
  gallerySurface: {
    label: "Gallery Surface",
    category: "gallery",
    type: "surface",
    defaultEnabled: false,
    defaultX: 4,
    defaultY: 7,
    defaultW: 4,
    defaultH: 3,
    minW: 1,
    minH: 1,
    maxW: 12,
    maxH: 17,
  },
  galleryTitle: {
    label: "Gallery Title Bubble",
    category: "gallery",
    type: "title",
    defaultEnabled: false,
    defaultText: "Photo Gallery",
    defaultX: 4.8,
    defaultY: 7.15,
    defaultW: 2.4,
    defaultH: 0.5,
    minW: 0.75,
    minH: 0.4,
    maxW: 12,
    maxH: 17,
  },
  galleryContent: {
    label: "Photo Grid",
    category: "gallery",
    type: "galleryGrid",
    defaultEnabled: false,
    defaultX: 4.25,
    defaultY: 7.75,
    defaultW: 3.5,
    defaultH: 1.85,
    minW: 1,
    minH: 0.75,
    maxW: 12,
    maxH: 17,
  },
  galleryLink: {
    label: "Gallery Link",
    category: "gallery",
    type: "galleryLink",
    defaultEnabled: false,
    defaultX: 4.35,
    defaultY: 9.55,
    defaultW: 2,
    defaultH: 0.45,
    minW: 0.75,
    minH: 0.35,
    maxW: 12,
    maxH: 17,
  },
  ...buildGalleryPhotoElements(),
  thoughtsSurface: {
    label: "Thoughts Surface",
    category: "thoughts",
    type: "surface",
    defaultEnabled: false,
    defaultX: 8,
    defaultY: 4,
    defaultW: 4,
    defaultH: 5,
    minW: 1,
    minH: 1,
    maxW: 12,
    maxH: 17,
  },
  thoughtsTitle: {
    label: "Thoughts Title Bubble",
    category: "thoughts",
    type: "title",
    defaultEnabled: false,
    defaultText: "Player Feed",
    defaultX: 8.7,
    defaultY: 4.25,
    defaultW: 2.6,
    defaultH: 0.5,
    minW: 0.75,
    minH: 0.4,
    maxW: 12,
    maxH: 17,
  },
  thoughtsComposer: {
    label: "Thought Composer",
    category: "thoughts",
    type: "thoughtsComposer",
    defaultEnabled: false,
    defaultX: 8.35,
    defaultY: 4.95,
    defaultW: 3.3,
    defaultH: 1.7,
    minW: 1,
    minH: 0.75,
    maxW: 12,
    maxH: 17,
  },
  thoughtsFeed: {
    label: "Thought Feed",
    category: "thoughts",
    type: "thoughtsFeed",
    defaultEnabled: false,
    defaultX: 8.25,
    defaultY: 6.9,
    defaultW: 3.5,
    defaultH: 1.9,
    minW: 1,
    minH: 0.75,
    maxW: 12,
    maxH: 17,
  },
};

export function isCustomTitleElementId(id) {
  return typeof id === "string" && id.startsWith(CUSTOM_TITLE_PREFIX);
}

export function getCompositionElementDef(id) {
  return PROFILE_COMPOSITION_ELEMENT_REGISTRY[id] || (isCustomTitleElementId(id) ? CUSTOM_TITLE_ELEMENT_DEF : null);
}

export function getDefaultCompositionElements() {
  return Object.entries(PROFILE_COMPOSITION_ELEMENT_REGISTRY).map(([id, def]) => ({
    id,
    category: def.category,
    type: def.type,
    enabled: def.defaultEnabled !== false,
    text: def.defaultText || "",
    x: def.defaultX,
    y: def.defaultY,
    w: def.defaultW,
    h: def.defaultH,
    style: {},
  }));
}
