export const PROFILE_PANEL_REGISTRY = {
  hero: {
    label: "Hero Card",
    minW: 4, minH: 3, maxW: 4, maxH: 8,
    defaultW: 4, defaultH: 5,
    required: true,
    draggable: false,
    resizable: true,
    resizableWidth: false,
  },
  identity: {
    label: "Social Links",
    minW: 3, minH: 2, maxW: 6, maxH: 5,
    defaultW: 4, defaultH: 3,
    required: false,
    draggable: true,
    resizable: true,
  },
  music: {
    label: "Music",
    minW: 3, minH: 2, maxW: 6, maxH: 5,
    defaultW: 4, defaultH: 3,
    required: false,
    draggable: true,
    resizable: true,
  },
  rankings: {
    label: "Rankings",
    minW: 3, minH: 2, maxW: 6, maxH: 4,
    defaultW: 4, defaultH: 2,
    required: false,
    draggable: true,
    resizable: true,
  },
  topFriends: {
    label: "Top Friends",
    minW: 3, minH: 2, maxW: 8, maxH: 4,
    defaultW: 4, defaultH: 2,
    required: false,
    draggable: true,
    resizable: true,
  },
  friends: {
    label: "Friends",
    minW: 3, minH: 2, maxW: 6, maxH: 5,
    defaultW: 4, defaultH: 3,
    required: false,
    draggable: true,
    resizable: true,
  },
  friendCode: {
    label: "Friend Code",
    minW: 3, minH: 2, maxW: 6, maxH: 4,
    defaultW: 4, defaultH: 3,
    required: false,
    draggable: true,
    resizable: true,
  },
  favoriteGame: {
    label: "Favorite Game",
    minW: 3, minH: 2, maxW: 6, maxH: 4,
    defaultW: 4, defaultH: 2,
    required: false,
    draggable: true,
    resizable: true,
  },
  gallery: {
    label: "Gallery",
    minW: 3, minH: 2, maxW: 8, maxH: 5,
    defaultW: 4, defaultH: 3,
    required: false,
    draggable: true,
    resizable: true,
  },
  thoughts: {
    label: "Thoughts",
    minW: 3, minH: 3, maxW: 8, maxH: 8,
    defaultW: 4, defaultH: 5,
    required: false,
    draggable: true,
    resizable: true,
  },
  about: {
    label: "About",
    minW: 3, minH: 2, maxW: 6, maxH: 4,
    defaultW: 4, defaultH: 2,
    required: false,
    draggable: true,
    resizable: true,
  },
  badges: {
    label: "Badges",
    minW: 3, minH: 1, maxW: 12, maxH: 4,
    defaultW: 4, defaultH: 2,
    required: false,
    draggable: true,
    resizable: true,
  },
};

export const KNOWN_PANEL_IDS = new Set(Object.keys(PROFILE_PANEL_REGISTRY));
